### PR TITLE
[WIP] Issue #1249 Force NTLM authentication

### PR DESCRIPTION
**Pull request by gbraad**
Fix for issue #1249 ?

### CODE REVIEW

**Comment by hferentschik** [comment]
retest this please

**Comment by hferentschik** [comment]
@gbraad, so is this something needed you think or just an experiment? Should this be added regardless of whether the reported issue is "user error"?

**Comment by gbraad** [comment]
I am not sure what the issue with the user is, but this doesn't hurt to test...

**Comment by hferentschik** [comment]
What exactly does it do?

**Comment by gbraad** [comment]
force authentication to happen with NTLM v1


```
$ man mount.cifs
...
sec=
           Security mode. Allowed values are:
           ·   none - attempt to connection as a null user (no name)
           ·   krb5 - Use Kerberos version 5 authentication
           ·   krb5i - Use Kerberos authentication and forcibly enable packet signing
           ·   ntlm - Use NTLM password hashing
           ·   ntlmi - Use NTLM password hashing and force packet signing
           ·   ntlmv2 - Use NTLMv2 password hashing
           ·   ntlmv2i - Use NTLMv2 password hashing and force packet signing
           ·   ntlmssp - Use NTLMv2 password hashing encapsulated in Raw NTLMSSP message
           ·   ntlmsspi - Use NTLMv2 password hashing encapsulated in Raw NTLMSSP message, and force packet signing

           The default in mainline kernel versions prior to v3.8 was sec=ntlm. In v3.8, the default was changed to sec=ntlmssp.

           If the server requires signing during protocol negotiation, then it may be enabled automatically. Packet signing may also be enabled automatically if it's enabled in /proc/fs/cifs/SecurityFlags.
```

the default is now `ntlmssp` and it might fail if trying to connect to an older default.

**Comment by hferentschik** [comment]
So you want to add  'sec=ntlm' just to see whether it makes a difference for issue #1249 specifically? I guess what I am concerned about is to merge this into the production code and breaking it for people for whom things actually work. In case it would make a difference for #1249, would be the plan to make this a config option in some form?

**Comment by gbraad** [comment]
Other issues related to WannaCry have been reported, so we might want to be able to force a `sec` method. Configurable would be a preferred way. I have the executable and tested this... so closing.

**Comment by hferentschik** [comment]
ok, thanks.

**Pull request closed without merging**
