### PR TITLE
Issue #2718 Add sleep time in millisecond instead seconds

### LINKED ISSUE #2718: Mistake in basic.feature file
### General information

Basic.feature contains an undefined step. The step uses time in seconds, however the implementation and matching accepts only values in ms.

### Expected

`And with up to "10" retries with wait period of "100ms" the "status code" of HTTP request to "/console" of OpenShift instance is equal to "200"`

### Actual

`And with up to "10" retries with wait period of "1s" the "status code" of HTTP request to "/console" of OpenShift instance is equal to "200"`

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #2718 

Steps to test the pull request

  1. 
  2. 
  3. 
  4.

### CODE REVIEW

**Comment by agajdosi** [comment]
@praveenkumar @LalatenduMohanty Let's merge this, it is ready.

**Comment by praveenkumar** [comment]
> this is not a typo

@gbraad you mean the commit message?

**Comment by LalatenduMohanty** [comment]
> this is not a typo

I am not sure what you mean to say. Can you please explain?

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by praveenkumar** [comment]
> I am not sure what you mean to say. Can you please explain?

@LalatenduMohanty  there was a typo in the commit message and it fixed so can be merged now.

**Pull request merged**
