### PR TITLE
Issue #878 Fail to escape password with special charachers

### PR DESCRIPTION
**Pull request by praveenkumar**
Basically the way sshCommander works is it will take the string as it is and then start ssh session. when it start session it is always be a new shell so if we want to escape special characters then we need to make sure string we we are passing should have `'<Password>'`.

### CODE REVIEW

**Comment by praveenkumar** [comment]
@LalatenduMohanty we need password in single quote only if contain special characters otherwise without quote it also works and that is already mentioned in the  troubleshooting guide.

**Comment by gbraad** [comment]
Would it hurt to always use single quotes?

**Comment by gbraad** [comment]
Already saw you changed the command description, but how about documentation about this?

**Comment by budhrg** [comment]
Looks like now having issue with password containing single quote. The password containing space, brackets seesm to be working.

```
Registering machine using subscription-manager
E0518 11:30:00.955732   16556 start.go:176] Error starting the VM: Error registering the VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username bgurung@redhat.com --password 'foo'bar' 
err     : exit status 1
output  : bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file
. Retrying.
Waiting for SSH to be av
```

**Comment by praveenkumar** [comment]
> Would it hurt to always use single quotes?

No it won't, but even you tell users then also they miss and only understand when face issue/failure :)

**Comment by praveenkumar** [comment]
> Looks like now having issue with password containing single quote. The password containing space, brackets seesm to be working.

Single quote anyway need escape and that understood.

**Comment by budhrg** [comment]
> Single quote anyway need escape and that understood.

I didn't get what it means. Is there anything here user need to do?

**Comment by praveenkumar** [comment]
> I didn't get what it means. Is there anything here user need to do? I tried even passing it as "foo\'bar".

if you want to escape single quote then for bash it should be `'"'"'` as escaped sequence. Can you try `'foo'"'"'bar` which should work.

**Comment by budhrg** [comment]
> With minishift start --username bgurung@redhat.com --password 'foo'"'"'bar'  

```
Registering machine using subscription-manager
E0518 11:57:13.451351   21442 start.go:176] Error starting the VM: Error registering the VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username bgurung@redhat.com --password 'foo'bar' 
err     : exit status 1
output  : bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file
. Retrying.
Waiting for SSH to be available...
```

**Comment by gbraad** [comment]
> No it won't, but even you tell users then also they miss and only understand when face issue/failure :)

Although you are right about this, maybe including this as part of the troubleshooting would help. "My password is not accepted? Here is what to do..."

**Comment by praveenkumar** [comment]
> Although you are right about this, maybe including this as part of the troubleshooting would help. "My password is not accepted? Here is what to do..."

Agree might be we need bit change from troubleshooting guide, we do have now if password contain special characters then do that...

**Comment by budhrg** [comment]
@praveenkumar , verified that single quote is working when passed as `"foo'\"'\"'bar"`

> Although you are right about this, maybe including this as part of the troubleshooting would help. "My password is not accepted? Here is what to do..."

:+1: , Might be a note in already existing troubleshooting guide that if your password contain single quote you need to pass it as per your shell. For bash, pass as `"foo'\"'\"'bar"`.

**Pull request merged**
