### PR TITLE
Issue #1613 use consistent Windows drive letters and prompts

### PR DESCRIPTION
**Pull request by robin-owen**
* Use `PS>` consistently for PowerShell
* Use `C:\>` consistently for Command Prompt
* Replace slashes in Windows-specific paths with backslashes
* Refer to the Minishift binary in Windows-specific contexts as `minishift.exe`

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I think I was wrong about PowerShell on Windows 7. https://blogs.technet.microsoft.com/heyscriptingguy/2011/01/07/how-do-i-install-powershell-on-windows-7-and-other-questions/. @minishift/minishift-dev Can anyone check on Windows7 that it has PowerShell.

**Comment by gbraad** [comment]
I think this is clear enough. Both the situations you mention are actually written as command prompt examples, and are not different in use between this and PowerShell


```diff
 -$ minishift config set warn-check-hyperv-driver true
 +C:\> minishift.exe config set warn-check-hyperv-driver true
```

```diff
 -$ minishift start --iso-url file://c:/path/to/image.iso
 +C:\> minishift.exe start --iso-url file://c:/path/to/image.iso
```

IN all the other cases it is addressed beforehand.

In text, it might be possible to mention that they do not differ.

**Comment by gbraad** [comment]
### Is PowerShell available on Windows 7?

Windows 7/Server 2008 R2 are the first Windows versions to come with PowerShell installed, by default. Windows PowerShell 2.0 needs to be installed on Windows Server 2008 and Windows Vista only. It is already installed on Windows Server 2008 R2 and Windows 7

Ref: https://blogs.technet.microsoft.com/heyscriptingguy/2011/01/07/how-do-i-install-powershell-on-windows-7-and-other-questions/, https://serverfault.com/questions/615275/in-which-version-of-windows-is-powershell-installed-by-default

**Comment by budhrg** [comment]
> Can anyone check on Windows7 that it has PowerShell.

@LalatenduMohanty , Yes the one our QE use has PowerShell.

**Pull request merged**
