### PR TITLE
Fix devfile registry template label

### PR DESCRIPTION
**Pull request by sleshchenko**
Sorry guys for introducing it in https://github.com/minishift/minishift/pull/3333/files#diff-bbf0404171dd76fd7527d27231269f1bR100
I'm not really aware if it affects any functionality but it would be good to have consistent labels =)

Steps to test the pull request

  1. Apply Che minishift addon
  2. Check is you're able to create and run workspaces

You may face some issues if you run your minishift on linux+KVM. More see https://github.com/minishift/minishift/pull/3333#issuecomment-530737439
MacOS or Linux+VirtualBox should work fine

### CODE REVIEW

**Comment by sleshchenko** [comment]
cc @anjannath

**Comment by anjannath** [comment]
@sleshchenko Ahh so sorry for the delay, i missed the notification!

**Comment by anjannath** [comment]
ok to test

**Comment by sleshchenko** [comment]
@anjannath Rebased onto master.

**Comment by gbraad** [comment]
What does this fix ? I see no reference to an issue ...

**Comment by sleshchenko** [comment]
@gbraad I fixes typo, I'm not sure that somewhere exist issue but such typo cause like devfile registry removing along with plugin registry... Or some another issue. I believe it should be merged.

**Comment by gbraad** [comment]
I am confused about this, as the initial message says: 

```
You may face some issues if you run your minikube on linux+KVM. More see #3333 (comment)
MacOS or Linux+VirtualBox should work fine
```

Not sure why minikube is mentioned. Also, i haven't been able to verify this, so an indication to this need. A filed issue is needed for any change we make to the codebase and included resources in the release.

**Comment by sleshchenko** [comment]
> Not sure why minikube is mentioned.

@gbraad Sorry, it's my fault. It's just typo and minishift should be there. Fixed.

**Comment by gbraad** [comment]
PR is out of sync with master and needs to include an issue number in the commit description. If none is given, the CI will fail.

**Comment by anjannath** [comment]
merged in https://github.com/minishift/minishift/commit/cc68e904319c281c106851a06667f71a137ce62d

**Pull request closed without merging**
