### PR TITLE
Issue #1841 Fix to provision OpenShift 3.6.1

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@praveenkumar you need to fix `func Test_DetermineOcVersion`

**Comment by gbraad** [comment]
what if `3.6.2` comes along? Does would mean we have to force a new point release to make it work... right?

**Comment by praveenkumar** [comment]
> what if 3.6.2 comes along? Does would mean we have to force a new point release to make it work... right?

I think minor version can be provisioned without any problem. This problem occurred there was some bug on `oc cluster up` but I am hoping it not going to happen so frequently. If again occurred then we might force new point.

**Comment by gbraad** [comment]
Do we have a related BZ issue for this? Might be important to have this as part of the issue description or even commit description.

I see no further issue here... however, this will result in a point release of Minishift, and if so, what else would have to go in? I guess the start error message for caching?

**Comment by LalatenduMohanty** [comment]
> what if 3.6.2 comes along? Does would mean we have to force a new point release to make it work... right?

I was also thinking the same. Ideally the version should be the last in the 3.6.x series. 

> Do we have a related BZ issue for this? Might be important to have this as part of the issue description or even commit description.

I think we should file an issue on this i.e. using 3.6.0 binary we can not provision 3.6.1  as this is an issue for sure.

**Comment by LalatenduMohanty** [comment]
Raised https://github.com/openshift/origin/issues/17821

**Comment by LalatenduMohanty** [comment]
@praveenkumar @gbraad IMO we should change `OPENSHIFT_VERSION = v3.6.0` to v3.6.1 in the Makefile. I understand that we would move to 3.7.0 in #1776  but with this PR v3.6.0 in Makefile does not look consistent in a way.

**Comment by gbraad** [comment]
I agree

**Pull request merged**
