### PR TITLE
Issue #204 Update install document

### PR DESCRIPTION
**Pull request by tylerkelly13**
Updating installation page. Issue referred to in note has been resolved for almost 5 months https://github.com/minishift/minishift/issues/204

### CODE REVIEW

**Comment by tylerkelly13** [comment]
Going to close and reopen to fix commit message

**Comment by LalatenduMohanty** [comment]
@tylerkelly13 I have opened an issue #1611 for this PR. Please use it in the commit message.

**Comment by LalatenduMohanty** [comment]
@tylerkelly13 please check https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc and hence once of the CI is failing
```
make validate_commits

go get -u github.com/vbatts/git-validation/...
git-validation -q -run short-subject,message_regexp='(Issue #[0-9]+ .*|cut v[0-9]+.[0-9]+.[0-9]+)' -range 204ce1930e8a86d0c5b5eabd1d8b8dbf8d9edac3...
 873276de - FAIL - commit message does not match "(Issue #[0-9]+ .*|cut v[0-9]+.[0-9]+.[0-9]+)"
1 commits to fix
make: *** [validate_commits] Error 1
```

**Comment by tylerkelly13** [comment]
Thanks Lalatendu.
Dived in and forgot to check the contributing guide.
Fixed up, and passing now under issue #1611, pr #1612

**Pull request closed without merging**
