### PR TITLE
Fix #154 remove unused variable from Makefile

### LINKED ISSUE #154: Unused variable in Makefile
Currently Makefile contain `PYTHON`, `BUILD_OS` and `BUILD_IMAGE` which have no use during any section of Makefile. I propose we should remove those unused variables and if requirement need those then add it.

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will remove unused variable from Makefile.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@praveenkumar minishift has inherited these from minikube `Makefile`. Do you know if updating K8s []1 and the Minishift has any inbter dependencies. 

[1] https://github.com/minishift/minishift/blob/master/UPDATE_KUBERNETES.md

**Comment by hferentschik** [comment]
@praveenkumar nice, I came to the same conclusion on my branch. I removed it there as well with a whole bunch of other Makefile changes.

**Comment by hferentschik** [comment]
@praveenkumar I'm going to merge this into the _cluster-up_ branch for now and then we can merge everything together into _master_ once the basic 'cluster up' is working. Does that work for you?

**Comment by praveenkumar** [comment]
@hferentschik yes that works :+1:

**Comment by hferentschik** [comment]
Merged to _cluser-up_ branch. Will be merged to master with changes for issue #141

**Pull request closed without merging**
