### PR TITLE
Issue #1682 Fix minishift architecture diagram integration docs.openshift.org

### LINKED ISSUE #1682: Minishift architecture diagram is not rendering due to permission issue
Seem to be permission issue 
screenshot from 2017-11-10 16-02-53

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1682

### CODE REVIEW

**Comment by budhrg** [comment]
@LalatenduMohanty Please confirm in Fedora.

**Comment by hferentschik** [comment]
@budhrg that's more like it ;-)

**Comment by LalatenduMohanty** [comment]
@budhrg I do not have my Fedora with me. So will suggest @praveenkumar or @gbraad to test it.

**Comment by hferentschik** [comment]
I think it is important to mention that one needs to test the docs.openshift.org build, not just the local docs build - https://docs.openshift.org/latest/minishift/contributing/writing-docs.html#integration-with-docs-openshift-org

**Comment by hferentschik** [comment]
@budhrg, an alternative is that you manually upload a docs tarball which includes this change. Then we can see whether this change really "fixes" the issues on docs.openshift.org. If so, we can merge it.

**Comment by budhrg** [comment]
>  an alternative is that you manually upload a docs tarball which includes this change. Then we can see whether this change really "fixes" the issues on docs.openshift.org. If so, we can merge it.

Works for me @hferentschik :smile:

**Comment by hferentschik** [comment]
> Tested locally. Working fine for me. Let's hope it work same in openshift.org too 

+1. Let's see tomorrow.

**Comment by praveenkumar** [comment]
@hferentschik @budhrg I can see now rendering happens as expected, should we merge it?

**Comment by LalatenduMohanty** [comment]
@budhrg @praveenkumar @hferentschik I can see the image properly rendered in https://docs.openshift.org/latest/minishift/using/basic-usage.html

**Pull request merged**
