### PR TITLE
Issue #722 Extracting Uninstallation section and creating a new...

### PR DESCRIPTION
**Pull request by Preeticp**
…document for it, so that this section is more visible to users.

### CODE REVIEW

**Comment by Preeticp** [comment]
Done @hferentschik, sorry had missed that.

**Comment by hferentschik** [comment]
> Done, sorry had missed that.

Cool. Could you please also rebase on master. There are conflicts in installing.adoc

**Comment by Preeticp** [comment]
Done @hferentschik

**Comment by hferentschik** [comment]
Merged, thanks

**Pull request merged**
