### PR TITLE
[Do not merge] Testing if integration tests are fine with 3.10

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by amitkrout** [comment]
Retest this please

**Comment by amitkrout** [comment]
Retest this please

**Comment by amitkrout** [comment]
@budhram Would you please check why ci job is pending for a long period

**Comment by agajdosi** [comment]
retest this please

**Comment by LalatenduMohanty** [comment]
Closing this in favor of https://github.com/minishift/minishift/issues/2658

**Pull request closed without merging**
