### PR TITLE
[WIP] Issue #590 Allow hyperv virtual switch as start option and env variable

### LINKED ISSUE #590: Allow selection of virtual switch for use with Hyper-V
Related to: #589

Allow selection of the Virtual Switch to use for deployment with Hyper-V. Needs to be compatible with the behavior with Docker Machine ([environment variables](https://docs.docker.com/machine/drivers/hyper-v/#environment-variables-and-default-values)) and the possible passthrough #305 

At this point there are no way to choose a virtual switch in HyperV for Minishift . Minishift uses the first virtual switch in the list for the Minishift VM. This will result in to failure if the virtual switch is not the intended switch for Minishift (e.g. not an external switch, not connected to external dhcp server etc).  So user who have multiple virtual switch are most likely to face this issue.

### PR DESCRIPTION
**Pull request by budhrg**
Fix #590 

Tested with :
- `MINISHIFT_HYPERV_VIRTUAL_SWITCH`  environment variable
- `--hyperv-virtual-switch` option in start command
- `minishift config set hyperv-virtual-switch switch_name`

Above three are working as expected.

Working on tests !

### CODE REVIEW

**Comment by hferentschik** [comment]
I don't get it? What happened to the generic approach? I thought we agreed that we try that or at least find out why it is not working. It seems wrong to add a driver specific option this way and it does not scale at all. 

If we merge this, how are we going about, if we find a generic solution to the problem? Adding is easy, taking something away once you exposed it as an API not so much.

**Comment by hferentschik** [comment]
Unless someone gives me an explanation on why a generic approach is not possible, this is a no go.

**Comment by hferentschik** [comment]
I think we can close this pull request. We are looking first at implementing a generic solution as part of #305

**Comment by budhrg** [comment]
> I think we can close this pull request. We are looking first at implementing a generic solution as part of #305

👍

**Pull request closed without merging**
