### PR TITLE
[Don't Merge] [WIP] Issue #1882 Fix user is part of Hyper-V admin check when user is in a domain

### LINKED ISSUE #1882: Preflight check: For corporate Windows users, Preflight Check for Hyper-V fails, when primary domain cannot be reached.
# General information
- Minishift version: 1.11.0 (1.11.0-windows-amd64)
- OS: Windows (10.0.15063)
- Hypervisor: Hyper-V
- Powershell version: 5.1.15063.726
- Local Administrator: yes

# Specific context
This problem ONLY occurs for corporate Winows users, when the user is NOT connected to the corporate network (primary domain cannot be reached).
Local Users are NOT affected.

# Steps to reproduce
1. Be detached from the corporate network
1. Setup minishift for Hyper-V as described on https://docs.openshift.org/latest/minishift/getting-started/installing.html & https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver
    - including adding the user to the Hyper-V administrators group `([adsi]"WinNT://./Hyper-V Administrators,group").Add("WinNT://$env:UserDomain/$env:Username,user")`
1. Start minishift (`.\minishift.exe start`)

# Expected
The Preflight check correctly identifies my user as part of the Hyper-V administrators group.
Minishift starts.
# Actual
Minishift fails to start
```
PS C:\Users\kavn\Downloads\minishift-1.11.0-windows-amd64> .\minishift.exe start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
```
# Caused by
This problem is caused by the powershell command executed by the preflight check (Line 377), as this powershell validation relies on network connectivity to the primary domain or AD-server.
https://github.com/minishift/minishift/blob/44599174664e8d7afa2e5e796a509b7ee4e1f694/cmd/minishift/cmd/start_preflight.go#L377

```
PS C:\WINDOWS\system32> @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")
Exception calling "IsInRole" with "1" argument(s): "The trust relationship between this workstation and the primary domain failed.
"
At line:1 char:1
+ @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIde ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SystemException
```

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #1882 
Check [#1882/Comment](https://github.com/minishift/minishift/issues/1882#issuecomment-363755290)

### CODE REVIEW

**Comment by gbraad** [comment]
Can you explain why do we need this?

**Comment by anjannath** [comment]
@gbraad so that we don't make the hyperv driver check WARN by default. Only WARN when the user is part of a domain.

**Comment by gbraad** [comment]
this means this function has side-effects. rather see the actual test modified

**Comment by anjannath** [comment]
@gbraad Yes this has side effects.  Lets see if i can modify the actual test and achieve the same behaviour.

**Comment by gbraad** [comment]
checking the new implementation...

**Comment by anjannath** [comment]
This is not needed anymore, there'll be a new patch from @paul-green.
refer #2047

**Pull request closed without merging**
