### PR TITLE
Issue #1279 Reduce time used in CI by using a prebuilt docs image

### LINKED ISSUE #1279: Reduce time used in CI by using a prebuilt document generation image
At the moment we use a `docker build` for a container, which used on CI to generate some of the documentation. The process of docker pull and docker build takes 8+ mins (of which 45 secs is the pull). This can be optimized by using a prebuilt image.

Note: I have access to the `minishift` namespace on docker hub IIRC.

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1279 

Using pre-built image - https://hub.docker.com/r/minishift/docs/

### CODE REVIEW

**Comment by budhrg** [comment]
cc @gbraad @LalatenduMohanty @praveenkumar @amitkrout @agajdosi 

### Without PR (https://ci.centos.org/job/minishift-pr/2122/consoleFull)
```
05:05 - 12:41 : Docs image build (~7:36 mins)
12:41 - 13:01 : Links check (21sec)
```
#### Total duration: (7:56mins)


### With PR (https://ci.centos.org/job/minishift-pr/2123/consoleFull)
```
05:05 - 06:06 : Docs image download (1:01 mins) 
06:06 - 06:25 : Links check (21 sec)
```
#### Total duration: (1:20 mins)

#### Decrease in PR build time : ~8mins

**Comment by budhrg** [comment]
### For those whose user id is not `1000` will get error locally. 
```
$ id -u
1001

$ make link_check_docs
cd docs && docker run -e OPENSHIFT_VERSION=v3.6.0 -e MINISHIFT_VERSION=1.6.0 -e CENTOS_ISO_VERSION=v1.2.0 -tiv /home/budhram/gowork/src/github.com/minishift/minishift/docs:/home/docs:Z minishift/docs link_check
Unable to find image 'minishift/docs:latest' locally
Trying to pull repository docker.io/minishift/docs ... 
sha256:8ea23a8425a93265fa38701cf67a2d9daa0c13c1b2bb8c4b1095700a12af3256: Pulling from docker.io/minishift/docs
Digest: sha256:8ea23a8425a93265fa38701cf67a2d9daa0c13c1b2bb8c4b1095700a12af3256
Status: Downloaded newer image for docker.io/minishift/docs:latest
mkdir -p build
pandoc --atx-headers --to=asciidoc --output=source/command-ref/minishift.adoc source/_tmp/minishift.md
pandoc: source/command-ref/minishift.adoc: openFile: permission denied (Permission denied)
rake aborted!
Command failed with status (1): [pandoc --atx-headers --to=asciidoc --outpu...]
/home/docs/Rakefile:48:in `block in <top (required)>'
Tasks: TOP => link_check => gen => markdown_to_asciidoc => asciidoc => source/command-ref/minishift.adoc
(See full trace by running task with --trace)
make: *** [Makefile:121: link_check_docs] Error 1
```

### One need to build image locally in that case: 
```
$ IMAGE_UID=1001 make build_docs_container 
cd docs && docker build --build-arg uid=1001 -t minishift/docs .
Sending build context to Docker daemon   4.8 MB
Step 1/21 : FROM ruby:2.4
 ---> 68de654ed5ee
[...]
Step 21/21 : CMD -T
 ---> Running in b6aa407ca93a
 ---> dc75297251d6
Removing intermediate container b6aa407ca93a
Successfully built dc75297251d6

$ IMAGE_UID=1001 make link_check_docs 
cd docs && docker run -e OPENSHIFT_VERSION=v3.6.0 -e MINISHIFT_VERSION=1.6.0 -e CENTOS_ISO_VERSION=v1.2.0 -tiv /home/budhram/gowork/src/github.com/minishift/minishift/docs:/home/docs:Z minishift/docs link_check
mkdir -p build
pandoc --atx-headers --to=asciidoc --output=source/command-ref/minishift.adoc source/_tmp/minishift.md
[...]
     updated  build/contributing/variables.html
     updated  build/contributing/ci.html
Project built successfully.
bundle exec htmlproofer build --only-4xx
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["build"] on *.html... 


Checking 117 external links...
Ran on 77 files!


HTML-Proofer finished successfully.
```

**Comment by gbraad** [comment]
The userid can be solved, but will look for this later (on phone now)

**Comment by gbraad** [comment]
Merged with 76e922ebda54b6d1f3148be2c97c97a3e851b949

**Comment by hferentschik** [comment]
AFAICT this breaks at least the consistency of the Makefile, since _build_docs_container_ only got removed from the _link_check_docs_ not from the others. Also where is the code which builds and deploys the _minishift/docs_ image?

**Comment by hferentschik** [comment]
I propose to reopen this issue. The change to the Makefile is breaking the target dependencies and makes the behaviour inconsistent. _link_check_docs_ needs also to depend on _build_docs_container_. Otherwise, depending on which goal you execute you might end up with different images. This is really hard to reason about. What if you want to change the CI script to run a different docs goal. Then you suddenly build the container again. There is no a tight coupliing between this particualr Makefile change and what the CentOS CI script happens to execute right now.

If you want to use a pre-build image why don't you just do a 'docker pull minishift/docs' prior to calling make. Now the image is cached and you can execute _any_ docs target w/o having to build the image first (on that note, 'minishift/docs' is probably a bad name for this image to begin with. It is ok while jsut used locally, but if you are going to push it to Docker Hub it should proably be renamed). 

Last but not least, if really build time is the issue, just execute the docs tasks directly using Rake. If we install the Ruby dependencies we can call execute the docs tasks w/o any containers. This is by far the fastest way. The only downside is that we loose the "verification" that the in container build works. 

@budhrg wdyt? Reopen?

**Comment by budhrg** [comment]
> @budhrg wdyt? Reopen?

Sure @hferentschik

**Pull request closed without merging**
