### PR TITLE
Issue #2155 Update docker-machine from 0.13.0 to 0.15.0

### PR DESCRIPTION
**Pull request by praveenkumar**
We have to make sure it doesn't have any issue from hyperV side.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Tested on macOS and works fine.  We need to test it on HyperV, KVM , Virtualbox before merging it. @praveenkumar What hypervisor you tested?

**Comment by praveenkumar** [comment]
@LalatenduMohanty I also tested on xhyve.

**Comment by gbraad** [comment]
Good to see this...

**Comment by anjannath** [comment]
@LalatenduMohanty @praveenkumar  working for KVM and Hyper-V as well.

**Pull request merged**
