### PR TITLE
Issue #2759 Add docker subnet as NO_PROX for openshift >= 3.10

### LINKED ISSUE #2759: Error during 'cluster up' execution: Error starting the cluster. ssh command error
### General information
Installing minishift v3.10.0 FAILS while previous v3.9.0 works just fine. I am installing behind the company proxy.

  * Minishift version: v3.10.0
  * OS: macOS
  * Hypervisor: xhyve

Steps to reproduce:
Run command -> 
$ minishift start --v=5 --openshift-version v3.10.0 --show-libmachine-logs

### Logs
-- Starting OpenShift cluster .-- Running 'oc' with: 'cluster up --routing-suffix 192.168.64.15.nip.io --base-dir /var/lib/minishift/base --http-proxy http://someproxycom:8090 --https-proxy http://someproxycom:8090 --no-proxy localhost,127.0.0.1,172.30.1.1,127.0.0.1,192.168.64.*,localhost,*.acme.com --public-hostname 192.168.64.15'
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/useridx/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.64.15 -o IdentitiesOnly=yes -i /Users/useridx/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
/var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.64.15.nip.io --base-dir /var/lib/minishift/base --http-proxy http://someproxycom:8090 --https-proxy http://someproxycom:8090 --no-proxy localhost,127.0.0.1,172.30.1.1,127.0.0.1,192.168.64.*,localhost,*.acme.com --public-hostname 192.168.64.15
...................................................................................SSH cmd err, output: exit status 1: Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Pulling image openshift/origin-control-plane:v3.10
Image pull complete
Pulling image openshift/origin-cli:v3.10
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 57% complete
Pulled 3/4 layers, 86% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-node:v3.10
Pulled 5/6 layers, 84% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.64.15 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0904 17:27:25.334775    2130 config.go:42] Running "create-master-config"
I0904 17:27:27.002527    2130 config.go:46] Running "create-node-config"
I0904 17:27:28.056946    2130 flags.go:30] Running "create-kubelet-flags"
I0904 17:27:28.504122    2130 run_kubelet.go:48] Running "start-kubelet"
I0904 17:27:28.642423    2130 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0904 17:28:21.646213    2130 interface.go:26] Installing "kube-proxy" ...
I0904 17:28:21.646825    2130 interface.go:26] Installing "kube-dns" ...
I0904 17:28:21.646838    2130 interface.go:26] Installing "openshift-apiserver" ...
I0904 17:28:21.646906    2130 apply_template.go:83] Installing "openshift-apiserver"
I0904 17:28:21.647886    2130 apply_template.go:83] Installing "kube-proxy"
I0904 17:28:21.649365    2130 apply_template.go:83] Installing "kube-dns"
I0904 17:28:24.758579    2130 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-apiserver"
I0904 17:29:13.783068    2130 run_self_hosted.go:224] openshift-apiserver available
I0904 17:29:13.783113    2130 interface.go:26] Installing "openshift-controller-manager" ...
I0904 17:29:13.783129    2130 apply_template.go:83] Installing "openshift-controller-manager"
I0904 17:29:16.205141    2130 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding centos-imagestreams ...
Adding router ...
Adding persistent-volumes ...
Adding web-console ...
Adding registry ...
Adding sample-templates ...
I0904 17:29:16.227076    2130 interface.go:26] Installing "centos-imagestreams" ...
I0904 17:29:16.227084    2130 interface.go:26] Installing "openshift-router" ...
I0904 17:29:16.227088    2130 interface.go:26] Installing "persistent-volumes" ...
I0904 17:29:16.227094    2130 interface.go:26] Installing "openshift-web-console-operator" ...
I0904 17:29:16.227099    2130 interface.go:26] Installing "openshift-image-registry" ...
I0904 17:29:16.227103    2130 interface.go:26] Installing "sample-templates" ...
I0904 17:29:16.227140    2130 interface.go:26] Installing "sample-templates/postgresql" ...
I0904 17:29:16.227146    2130 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I0904 17:29:16.227150    2130 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I0904 17:29:16.227154    2130 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I0904 17:29:16.227158    2130 interface.go:26] Installing "sample-templates/rails quickstart" ...
I0904 17:29:16.227162    2130 interface.go:26] Installing "sample-templates/mongodb" ...
I0904 17:29:16.227166    2130 interface.go:26] Installing "sample-templates/mariadb" ...
I0904 17:29:16.227169    2130 interface.go:26] Installing "sample-templates/mysql" ...
I0904 17:29:16.227173    2130 interface.go:26] Installing "sample-templates/sample pipeline" ...
I0904 17:29:16.227177    2130 interface.go:26] Installing "sample-templates/django quickstart" ...
I0904 17:29:16.227182    2130 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I0904 17:29:16.227228    2130 apply_list.go:68] Installing "sample-templates/jenkins pipeline ephemeral"
I0904 17:29:16.227347    2130 apply_list.go:68] Installing "centos-imagestreams"
I0904 17:29:16.235731    2130 apply_list.go:68] Installing "sample-templates/rails quickstart"
I0904 17:29:16.236460    2130 apply_template.go:83] Installing "openshift-web-console-operator"
I0904 17:29:16.237219    2130 apply_list.go:68] Installing "sample-templates/postgresql"
I0904 17:29:16.237356    2130 apply_list.go:68] Installing "sample-templates/cakephp quickstart"
I0904 17:29:16.237500    2130 apply_list.go:68] Installing "sample-templates/dancer quickstart"
I0904 17:29:16.237663    2130 apply_list.go:68] Installing "sample-templates/nodejs quickstart"
I0904 17:29:16.237986    2130 apply_list.go:68] Installing "sample-templates/sample pipeline"
I0904 17:29:16.238118    2130 apply_list.go:68] Installing "sample-templates/mongodb"
I0904 17:29:16.238246    2130 apply_list.go:68] Installing "sample-templates/mariadb"
I0904 17:29:16.245775    2130 apply_list.go:68] Installing "sample-templates/mysql"
I0904 17:29:16.246058    2130 apply_list.go:68] Installing "sample-templates/django quickstart"
I0904 17:29:25.838473    2130 interface.go:41] Finished installing "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/mongodb" "sample-templates/mariadb" "sample-templates/mysql" "sample-templates/sample pipeline" "sample-templates/django quickstart" "sample-templates/jenkins pipeline ephemeral"
E0904 17:34:27.744161    2130 interface.go:34] Failed to install "openshift-web-console-operator": timed out waiting for the condition
I0904 17:34:27.744817    2130 interface.go:41] Finished installing "centos-imagestreams" "openshift-router" "persistent-volumes" "openshift-web-console-operator" "openshift-image-registry" "sample-templates"
Error: timed out waiting for the condition

**Error during 'cluster up' execution: Error starting the cluster. ssh command error:**
command : /var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.64.15.nip.io --base-dir /var/lib/minishift/base --http-proxy http://someproxycom:8090 --https-proxy http://someproxycom:8090 --no-proxy localhost,127.0.0.1,172.30.1.1,127.0.0.1,192.168.64.*,localhost,*.acme.com --public-hostname 192.168.64.15
err     : exit status 1

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #2759

Steps to test the pull request

  1. minishift start --http-proxy <proxy_uri> => should now works for 3.10

### CODE REVIEW

**Comment by praveenkumar** [comment]
retest this please.

**Comment by agajdosi** [comment]
Using the binary with proxy and cluster goes up just fine on Fedora. However when I tried integration tests, I noticed that there are some connections to rubygems.org missing during the deployment of ruby-ex. It is possible that the configuration is not used by OKD inside of the containers:
```
  Scenario: User can deploy application ruby-ex to namespace ruby # features/proxy.feature:41
    And proxy log should contain "Accepting CONNECT to bundler.rubygems.org:443" # features/proxy.feature:50
      Error: Output did not match. Expected: 'Accepting CONNECT to bundler.rubygems.org:443', Actual: '2018/09/21 [141] INFO: Running 0 CONNECT handlers [...]
(no URIs from ruby world here..)
```

**Comment by praveenkumar** [comment]
@agajdosi can you try deploying that app manually after you run minishift with proxy?

**Comment by agajdosi** [comment]
@praveenkumar On which port does that proxy have traffic log? Can't find it now.

**Comment by praveenkumar** [comment]
retest this please.

**Comment by LalatenduMohanty** [comment]
> @praveenkumar On which port does that proxy have traffic log? Can't find it now.

Is this resolved now?

**Comment by gbraad** [comment]
I would suggest calling this `Add container subnet as NO_PROXY; allows OpenShift >= 3.10 to deploy`

**Comment by LalatenduMohanty** [comment]
CI failure https://ci.centos.org/job/minishift-pr/4985/console

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by praveenkumar** [comment]
retest this please.

**Pull request merged**
