### PR TITLE
Issue #308 Update needed for rhel custom provisioner to accommodate changes for latest docker

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch adds addition options which required for latest docker for RHEL.

### CODE REVIEW

**Comment by hferentschik** [comment]
Is this something we need to synchronize with https://github.com/minishift/minishift-centos-iso/pull/85. So we need to first merge the patch for minishift-centos-iso before we merge this?

Seems on the CentOS ISO we just need to merge this pull request and add CI integration, then we could do a CR 1 release.

@budhrg where are we at with the CI integration for the CentOS ISO repo? Can we enable this?

**Comment by budhrg** [comment]
>  where are we at with the CI integration for the CentOS ISO repo? Can we enable this?

@hferentschik , we can enable it. just waiting for PR https://github.com/minishift/minishift-b2d-iso/pull/18 to get merge, then i will will similar smoke test for centos iso, integegrate CI and test the PR again.
Make sense?

**Comment by hferentschik** [comment]
> , we can enable it. just waiting for PR minishift/minishift-b2d-iso#18 to get merge, then i will add similar smoke tests for centos iso

ok

**Comment by hferentschik** [comment]
@budhrg, done

**Comment by budhrg** [comment]
> @budhrg, done

Cool, on my way to enable CI for centos iso repo

**Comment by hferentschik** [comment]
@budhrg see also https://github.com/minishift/minishift-b2d-iso/issues/22

**Comment by praveenkumar** [comment]
@hferentschik @budhrg  this is change from rhel image side not from CentOS side. For this PR I don't think it make much sense to check anything from centos side.

Down the line when CentOS tree also get updated (which takes around a week) then will send another PR for CentOS specific and can be tested with CI.

**Comment by hferentschik** [comment]
Merged, thanks.

**Pull request merged**
