### PR TITLE
Issue #1531 Step for restart of OpenShift fails on Windows

### PR DESCRIPTION
**Pull request by agajdosi**
Quick fix for the issue we have on nightly builds on Windows slave.

### CODE REVIEW

**Comment by agajdosi** [comment]
I have verified this on Fedora 25 and Windows 7.

Needs to be verified on Windows 10 and macOS.

**Comment by hferentschik** [comment]
Looking good to me

**Comment by agajdosi** [comment]
@hferentschik Verified on Windows 10 and macOS. If that looks fine for you, please merge it.

**Comment by hferentschik** [comment]
Merged, thanks.

**Pull request closed without merging**
