### PR TITLE
Issue #205 Updating existing integration framework

### PR DESCRIPTION
**Pull request by hferentschik**
Addresses issue #205

- Keeping a small subset of working test which don't need kubectl or depend on other external tools
- Change type MinikubeRunner to Minishiftrunner and adjusted variable names

Test are slow, but at least work again. Also a step forward to resolve issue #168.
The remaining tests and framework code will form the base for issue #135

### CODE REVIEW

**Comment by budhrg** [comment]
@hferentschik  I am getting issue related to validation of certificates.

Anything I am missing?
```
$ make integration 
find: paths must precede expression: minishift-centos.iso
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
glide install -v
[INFO]  Downloading dependencies. Please wait...
.......
[INFO]  Removing Godep rewrites for /home/budhram/gowork/src/github.com/minishift/minishift/vendor/github.com/openshift/source-to-image
mkdir -p ./out/linux-amd64
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build --installsuffix cgo -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.1 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/linux-amd64/minishift ./cmd/minikube
go test -timeout 3600s github.com/minishift/minishift/test/integration --tags=integration

EXTRA_ARGS='
--label provider=virtualbox
--insecure-registry 172.30.0.0/16

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

export "FOO=BAR"
export "BAZ=BAT"


--- FAIL: TestStartStop (141.27s)
  util.go:44: Error running command: start --vm-driver virtualbox E0103 13:06:41.656516   23394 start.go:131] Error starting machine: Error creating. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
    You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
    Be advised that this will trigger a Docker daemon restart which might stop running containers.
    . Retrying.
    E0103 13:07:46.223842   23394 start.go:238] Error starting 'cluster up':  exit status 1
    . Output: Starting local OpenShift cluster...
    Distribution doesn't support registration
    Provisioning OpenShift via '/home/budhram/.minishift/cache/oc/v1.3.1/oc [cluster up]'
    -- Checking OpenShift client ... OK
    -- Checking Docker client ... OK
    -- Checking Docker version ... OK
    -- Checking for existing OpenShift container ... OK
    -- Checking for openshift/origin:v1.3.1 image ... 
       Pulling image openshift/origin:v1.3.1
       Pulled 0/3 layers, 3% complete
       Pulled 1/3 layers, 60% complete
       Pulled 2/3 layers, 86% complete
       Pulled 3/3 layers, 100% complete
       Extracting
       Image pull complete
    -- Checking Docker daemon configuration ... OK
    -- Checking for available ports ... OK
    -- Checking type of volume mount ... 
       Using Docker shared volumes for OpenShift volumes
    -- Creating host directories ... OK
    -- Finding server IP ... 
       Using 192.168.99.100 as the server IP
    -- Starting OpenShift container ... 
       Creating initial OpenShift configuration
       Starting OpenShift using container 'origin'
       Waiting for API server to start listening
       OpenShift server started
    -- Installing registry ... OK
    -- Installing router ... OK
    -- Importing image streams ... OK
    -- Importing templates ... OK
    -- Login to server ... FAIL
       Error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
FAIL
FAIL  github.com/minishift/minishift/test/integration 431.022s
Makefile:93: recipe for target 'integration' failed
make: *** [integration] Error 1
```

**Comment by hferentschik** [comment]
Try again. Make sure to have a clean minishift directory before running it. Right now tests are run against ~/.minishift. This needs to change, but atm I just want it to run again. As said, there are more changes coming up.

**Comment by budhrg** [comment]
> Try again. Make sure to have a clean minishift directory before running it. 

Even not working and getting same error related to cert validation after removing `.minishift` directory.

**Comment by hferentschik** [comment]
@budhrg not sure what to say. Does _minishift start --vm-driver=virtualbox_ work for you? This does not look like an issue related to this pull request. This pull request does not change in any ways how provisioning works. 

@LalatenduMohanty @praveenkumar - could you try to run this as well? Make sure to run `minishift delete first and maybe delete the _cache_ directory as well. I will address the issue of integration test re-using the default directory in another pull request.
For all I can tell, it should pass (with VirtualBox). It takes a bit over 10min on my machine, hence I had to increase the default test timeout.

On a CI system the current use of the default directory should be no issue. Hence, it would be awesome if we could CentOS CI up and running. There we could run the tests on an independent server. 

In fact, it might not even be so important whether this actually passes or not. As mentioned this is an intermediate step. Just culling down what we have, keeping some basic infrastructure code which I think we can use for resolving issue #135. The really useful things to keep here imo are _MinishiftRunner_ and _OcRunner_. The tests which I kept might eventually be replaced by something else. WDYT?

**Comment by praveenkumar** [comment]
@hferentschik I will try that first thing tomorrow and let you know the results. @budhrg you used Linux for testing or windows?

**Comment by hferentschik** [comment]
>  I will try that first thing tomorrow and let you know the results.

ok

**Comment by budhrg** [comment]
> @hferentschik I will try that first thing tomorrow and let you know the results. @budhrg you used Linux for testing or windows?

Linux

**Comment by praveenkumar** [comment]
@budhrg @hferentschik Tested on Linux worked as expected.

```
...
[INFO]	Removing Godep rewrites for /home/prkumar/work/github/practice/go/src/github.com/minishift/minishift/vendor/github.com/google/cadvisor
[INFO]	Removing Godep rewrites for /home/prkumar/work/github/practice/go/src/github.com/minishift/minishift/vendor/github.com/opencontainers/runc
[INFO]	Removing Godep rewrites for /home/prkumar/work/github/practice/go/src/github.com/minishift/minishift/vendor/github.com/openshift/source-to-image
mkdir -p ./out/linux-amd64
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build --installsuffix cgo -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.1 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/linux-amd64/minishift ./cmd/minikube
go test -timeout 3600s github.com/minishift/minishift/test/integration --tags=integration
ok  	github.com/minishift/minishift/test/integration	489.809s
```

**Comment by hferentschik** [comment]
> Tested on Linux worked as expected.

Cool. Thanks. If there are no other comments regarding this cleanup, I am going to merge it.

**Pull request merged**
