### PR TITLE
[WIP] Issue #1327 Coolstore integration test failed with timeout issue

### PR DESCRIPTION
**Pull request by amitkrout**
Run it on minishift master
```
$ make integration GODOG_OPTS="-tags coolstore"
go install -pkgdir=/Users/amit/go/src/github.com/minishift/minishift/out/bindata -ldflags="-X github.com/minishift/minishift/pkg/version.minishiftVersion=1.6.0 -X github.com/minishift/minishift/pkg/version.b2dIsoVersion=v1.2.0 -X github.com/minishift/minishift/pkg/version.centOsIsoVersion=v1.2.0 -X github.com/minishift/minishift/pkg/version.minikubeIsoVersion=v0.24.0 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v3.6.0 -X github.com/minishift/minishift/pkg/version.commitSha=6f8471c4" ./cmd/minishift
mkdir -p /Users/amit/go/src/github.com/minishift/minishift/out/integration-test
go test -timeout 3600s github.com/minishift/minishift/test/integration --tags=integration -v -args --test-dir /Users/amit/go/src/github.com/minishift/minishift/out/integration-test --binary /Users/amit/go/bin/minishift --run-before-feature="" --tags basic -tags coolstore
Test run using Boot2Docker iso image.
Log successfully started, logging into: /Users/amit/go/src/github.com/minishift/minishift/out/test-results/integration_2017-10-9_17:23:30.log
Running Integration test in: /Users/amit/go/src/github.com/minishift/minishift/out/integration-test
Using binary: /Users/amit/go/bin/minishift
Feature: Basic
.
.
Feature: Cool Store

  In order to test Minishift under load
  I need to setup a test environment
  Using CentOS and 4G of memory
  After which I will import image streams
  Finally I will deploy the Cool Store
  Scenario: User enables the 'xpaas' add-on and creates a Minishift instance # features/coolstore.feature:9
    Given Minishift has state "Does Not Exist"                               # integration_test.go:159 -> *Minishift.shouldHaveState
    When executing "minishift addons enable xpaas"                           # integration_test.go:161 -> *Minishift.executingMinishiftCommand
    Then stdout should contain                                               # integration_test.go:655 -> commandReturnShouldContainContent
      """
      Add-on 'xpaas' enabled
      """
    When executing "minishift start --memory 4096" succeeds                  # integration_test.go:705 -> executingMinishiftCommandSucceedsOrFails
    Then Minishift should have state "Running"                               # integration_test.go:159 -> *Minishift.shouldHaveState
  Scenario: User creates a project and deploys CoolStore                                # features/coolstore.feature:19
    Given Minishift has state "Running"                                                 # integration_test.go:159 -> *Minishift.shouldHaveState
    When executing "oc new-project coolstore" succeeds                                  # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should contain                                                          # integration_test.go:655 -> commandReturnShouldContainContent
      """
      Now using project "coolstore"
      """
    When executing "oc create -f ./templates/coolstore.yaml" succeeds                   # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should contain                                                          # integration_test.go:655 -> commandReturnShouldContainContent
      """
      template "coolstore" created
      """
    When executing "oc new-app --template=coolstore" succeeds                           # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should contain                                                          # integration_test.go:655 -> commandReturnShouldContainContent
      """
      Success
      """
    When services "web-ui, inventory, catalog, cart, coolstore-gw" rollout successfully # integration_test.go:185 -> *Minishift.rolloutServicesSuccessfully
    Then executing "oc status -v" succeeds                                              # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    And stdout should not contain                                                       # integration_test.go:659 -> commandReturnShouldNotContainContent
      """
      has failed
      """
  Scenario: User is able to interact with the deployed services from the API gateway                # features/coolstore.feature:43
    Given Minishift has state "Running"                # integration_test.go:159 -> *Minishift.shouldHaveState
    When setting scenario variable "coolstore-gw" to the stdout from executing "oc get pods -o name -l application=coolstore-gw" # integration_test.go:179 -> *Minishift.setVariableExecutingOcCommand
    Then scenario variable "coolstore-gw" should not be empty                # integration_test.go:679 -> variableShouldNotBeEmpty
    When executing "oc rsh $(coolstore-gw) curl -sSL http://catalog:8080/api/products" succeeds                # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should not contain                # integration_test.go:659 -> commandReturnShouldNotContainContent
      """
      threw exception
      """
    And stdout should contain                # integration_test.go:655 -> commandReturnShouldContainContent
      """
      Fedora
      """
    When executing "oc rsh $(coolstore-gw) curl -sSL http://inventory:8080/api/availability/329299" succeeds                # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should contain                # integration_test.go:655 -> commandReturnShouldContainContent
      """
      Raleigh
      """
    When executing "oc rsh $(coolstore-gw) curl -sSL http://cart:8080/api/cart/FOO" succeeds                # integration_test.go:701 -> executingOcCommandSucceedsOrFails
    Then stdout should contain                # integration_test.go:655 -> commandReturnShouldContainContent
      """
      cartTotal
      """
  Scenario: User stops and deletes the Minishift instance # features/coolstore.feature:67
    Given Minishift has state "Running"                   # integration_test.go:159 -> *Minishift.shouldHaveState
    When executing "minishift stop" succeeds              # integration_test.go:705 -> executingMinishiftCommandSucceedsOrFails
    Then Minishift should have state "Stopped"            # integration_test.go:159 -> *Minishift.shouldHaveState
    When executing "minishift delete --force" succeeds    # integration_test.go:705 -> executingMinishiftCommandSucceedsOrFails
    Then Minishift should have state "Does Not Exist"     # integration_test.go:159 -> *Minishift.shouldHaveState
.
.
4 scenarios (4 passed)
30 steps (30 passed)
27m52.738603965s
testing: warning: no tests to run
PASS
ok      github.com/minishift/minishift/test/integration 1673.198s
$
```

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Marking WIP as we want to see if this passes in ci.centos.org first.

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by amitkrout** [comment]
Issue referred to https://github.com/jbossdemocentral/coolstore-microservice/issues/90

**Comment by budhrg** [comment]
Should be merged after https://github.com/minishift/minishift/issues/1396 fix otherwise it will increase PR build time a lot

**Comment by amitkrout** [comment]
ci re triggers automatically once i update the branch. This time all coolstore scenario passed but proxy feature failed to execute due to time out issue. Probably we need to increase the default time out to 5400 or more.  

log: https://ci.centos.org/job/minishift-pr/2211/consoleFull

**Comment by budhrg** [comment]
> feature failed to execute due to time out issue. Probably we need to increase the default time out to 5400 or more.

@amitkrout , since we are working on splitting into multiple jobs https://github.com/minishift/minishift/issues/1396, i suggest to run specific tags here.

**Comment by LalatenduMohanty** [comment]
@amitkrout I am closing this PR as we are doing now with respect to this issue. Please open a new PR when there is some new development.

**Comment by amitkrout** [comment]
@LalatenduMohanty On my local setup i can not see the time out issue with this pr. Coolstore images are deployed successfully, however the issue ```threw exception``` we are facing is with pod services and this occurs intermittently that causes the coolstore failure. IMO we can merge the coolstore.yaml file keeping rest intact i.e no change in make file. For ```threw exception``` a new issue can be created in minishift repo. WDYT?

**Comment by gbraad** [comment]
@amitkrout you had created an upstream issue for the "threw exception" ?

**Comment by amitkrout** [comment]
@gbraad yes. The issue was created on coolstore-microservice
 (https://github.com/jbossdemocentral/coolstore-microservice/issues/90) not in minishift repo.

**Pull request closed without merging**
