### PR TITLE
Issue #1633 Display sorted list in the output of profile list

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Output looks below now
```
$ minishift profile list
- a		    Does Not Exist
- b		    Does Not Exist
- minishift	    Running		(Active)

```

**Comment by hferentschik** [comment]
@LalatenduMohanty LGTM, go ahead and merge

**Comment by hferentschik** [comment]
Maybe adjust the commit message "Display profile names in alphabetical order"

**Comment by LalatenduMohanty** [comment]
@hferentschik updated the commit message ,waiting for CI to finish.

**Comment by hferentschik** [comment]
> updated the commit message ,waiting for CI to finish.

+1 Not sure whether some profile integration tests would be impacted. BTW, it would be nice to put the alphabetical order into a unit test and/or integration test, so that it becomes clear that this order is intentional. cc @amitkrout

**Pull request merged**
