### PR TITLE
Issue #2335 - Define timeout of imageExportShouldComplete in feature

### PR DESCRIPTION
**Pull request by agajdosi**
Fix : #2335

### CODE REVIEW

**Comment by agajdosi** [comment]
retest this please

**Comment by agajdosi** [comment]
retest please

**Comment by agajdosi** [comment]
@LalatenduMohanty Seems this can be merged, please take a look.

**Comment by budhrg** [comment]
Hi @agajdosi , Why `-` (hyphen) in commit message? We don't have such form yet :)

**Comment by agajdosi** [comment]
@budhrg totally unsure why :smile_cat: fixed now

**Comment by LalatenduMohanty** [comment]
@agajdosi LGTM

**Pull request merged**
