### PR TITLE
[WIP] Issue #1058 Make minikube ISO usable for Minishift

### PR DESCRIPTION
**Pull request by praveenkumar**
Addresses issue #1058

### CODE REVIEW

**Comment by praveenkumar** [comment]
This PR is able to start the VM and then pull openshift images but looks like iso need some more changes to make it work currently if you try this PR against minikube iso then it will throw below error.

```
- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 48% complete
   Pulled 2/3 layers, 67% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.185 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     Last 10 lines of "origin" container log:
     I0622 12:08:14.466090    3393 factory.go:54] Registering systemd factory
     I0622 12:08:14.469810    3393 factory.go:86] Registering Raw factory
     I0622 12:08:14.470544    3393 manager.go:1106] Started watching for new ooms in manager
     I0622 12:08:14.483870    3393 oomparser.go:185] oomparser using systemd
     I0622 12:08:14.520155    3393 manager.go:288] Starting recovery of all containers
     I0622 12:08:14.523743    3393 kubelet_node_status.go:230] Controller attach/detach is disabled for this node; Kubelet will attach and detach volumes
     I0622 12:08:14.604529    3393 node.go:359] Starting DNS on 0.0.0.0:53
     I0622 12:08:14.604685    3393 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
     I0622 12:08:14.604786    3393 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
     I0622 12:08:14.604963    3393 logs.go:41] skydns: listen udp 0.0.0.0:53: bind: address already in use
```

**Comment by hferentschik** [comment]
Is this something we are actively working on or should we close this pull request for now?

**Comment by praveenkumar** [comment]
@hferentschik not right now might be in next sprint.

**Comment by hferentschik** [comment]
Closing this pull request since we are not actively working on this for now.

**Comment by budhrg** [comment]
@praveenkumar , I am getting different errors now.
```
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 77% complete
   Pulled 2/3 layers, 97% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.155 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... FAIL
   Error: cannot update privileged SCC
   Details:
     Last 10 lines of "origin" container log:
     I0822 13:28:05.970980    3878 kubelet_node_status.go:74] Attempting to register node 192.168.42.155
     I0822 13:28:05.998750    3878 manager.go:293] Recovery completed
     I0822 13:28:06.008210    3878 rkt.go:56] starting detectRktContainers thread
     I0822 13:28:06.141308    3878 kubelet_node_status.go:77] Successfully registered node 192.168.42.155
     E0822 13:28:06.160324    3878 kubelet.go:1643] Failed to check if disk space is available on the root partition: failed to get fs info for "root": error trying to get filesystem Device for dir /var/lib/minishift/openshift.local.volumes: err: could not find device with major: 0, minor: 1 in cached partitions map
     I0822 13:28:07.262883    3878 node.go:501] Started Kubernetes Proxy on 0.0.0.0
     I0822 13:28:07.370421    3878 node.go:359] Starting DNS on 0.0.0.0:53
     I0822 13:28:07.381635    3878 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
     I0822 13:28:07.381717    3878 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
     I0822 13:28:07.381988    3878 logs.go:41] skydns: listen udp 0.0.0.0:53: bind: address already in use


   Caused By:
     Error: Put https://192.168.42.155:8443/api/v1/securitycontextconstraints/privileged: read tcp 192.168.42.1:34368->192.168.42.155:8443: read: connection reset by peer
Error during post cluster up configuration: Unable to add sudoer role

```

**Pull request closed without merging**
