### PR TITLE
Issue #3002 pass VBOX_MSI_INSTALL_PATH env to systray process

### LINKED ISSUE #3002: Preflight check returns false negative through systemtray minishift start
### General information

  * Minishift version: minishift-systemtray-1.27.0-windows-amd64
  * OS: Windows10
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Use minishift tray bit
  2. minishift start --vm-driver virtualbox
  3. Stop minishift from tray icon
  4. Then start it from tray icon

### Expected
minishift should run

### Actual
Preflight checks fails on virtualbox installation status

screen shot 2018-11-14 at 3 23 30 pm

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #3002 

/cc @amitkrout @agajdosi Could you guys verify if this fixes the issue both in windows 7 and 10

### CODE REVIEW

**Comment by gbraad** [comment]
If not sure, please add WIP to the title

**Comment by agajdosi** [comment]
@anjannath Can you please provide us the binaries? I think the system-tray ones are not part of builds here.

**Comment by anjannath** [comment]
@agajdosi Ahh.. sorry, i forgot to do that, the builds in circle ci has the binaries, but for some reason the status is not show here :-/ anyways.. here's the [windows binary](https://133-103576108-gh.circle-artifacts.com/0/ms/windows-amd64/systemtray/minishift.exe)

**Comment by agajdosi** [comment]
Works for me on Windows 7.

**Comment by amitkrout** [comment]
Works on Wimdows10 too

**Comment by LalatenduMohanty** [comment]
@anjannath Not sure why circle ci is not running for the PR. Can you try force push to see if circle CI responds.

**Pull request merged**
