### PR TITLE
[WIP] Issue #2005 something related to CI stuff

### LINKED ISSUE #2005: Upload integration tests logs on artifact server for nightly job
This is kind of adding an assist to debug nightly job failures.
Right now we don't store any artifacts of nightly jobs
https://github.com/minishift/minishift/blob/c5ad41134f490ff6d3c5ff9ae7cf5f7285bbf8c4/centos_ci.sh#L343-L346

### PR DESCRIPTION
**Pull request by budhram**
Fixes #2005

### CODE REVIEW

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
Will be working on it.

**Comment by gbraad** [comment]
What does this solve?

**Pull request closed without merging**
