### PR TITLE
Issue #1363, keeps iso-url unchanged to work with case sensitive urls

### LINKED ISSUE #1363: shortnames broke case-sensitive iso-urls
Issue #1033 added a new function where it changes the parameter for iso-url to all lowercase. This breaks when file path is case sensitive.
```
func determineIsoUrl(iso string) string {
	iso = strings.ToLower(iso)  <<<--------------
	isoNotSpecified := ""

	switch iso {
	case minishiftConstants.B2dIsoAlias, isoNotSpecified:
		iso = constants.DefaultB2dIsoUrl
	case minishiftConstants.CentOsIsoAlias:
		iso = constants.DefaultCentOsIsoUrl
	default:
		if !(govalidator.IsURL(iso) || strings.HasPrefix(iso, "file:")) {
			fmt.Println()
			atexit.ExitWithMessage(1, unsupportedIsoUrlFormat)
		}
	}

	return iso <<<-------
}
```

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #1363

### CODE REVIEW

**Comment by gbraad** [comment]
add to whitelist

**Comment by gbraad** [comment]
Is it possible to add some testcases?

**Comment by gbraad** [comment]
Please add cases to

https://github.com/minishift/minishift/blob/de69cc7b191d37587a8af0bc2c01c64885a6615d/cmd/minishift/cmd/start_test.go#L397

And

https://github.com/minishift/minishift/blob/de69cc7b191d37587a8af0bc2c01c64885a6615d/cmd/minishift/cmd/start_test.go#L420

**Comment by LalatenduMohanty** [comment]
@anjannath we can add another URLs in 

``` diff
func TestDetermineIsoUrl(t *testing.T) {
	var isoTests = []struct {
		in  string
		out string
	}{
		{"", constants.DefaultB2dIsoUrl},
		{"b2d", constants.DefaultB2dIsoUrl},
		{"B2D", constants.DefaultB2dIsoUrl},
		{"centos", constants.DefaultCentOsIsoUrl},
		{"CentOs", constants.DefaultCentOsIsoUrl},
		{"http://my.custom.url/myiso.iso", "http://my.custom.url/myiso.iso"},
		{"https://my.custom.url/myiso.iso", "https://my.custom.url/myiso.iso"},
		{"file://somewhere/on/disk", "file://somewhere/on/disk"},
++		{"file://somewhere/On/disk", "file://somewhere/On/disk"},
	}
```

**Comment by LalatenduMohanty** [comment]
@anjannath Also please fix the commit message as it contains a `,` in ` Issue #1363, keeps iso-url unchanged to work with case sensitive urls `.  Suggestion for commit message ` Issue #1363, Fix for iso-url to work with case sensitive urls `

**Comment by anjannath** [comment]
@LalatenduMohanty Thanks :) I'll  make the changes and update the PR.

**Pull request closed without merging**
