### PR TITLE
Issue #1148 Reference the latest OpenShift doc

### PR DESCRIPTION
**Pull request by liangxia**
Reference oc usage and authentication concept to the latest OpenShift doc.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@liangxia Thanks for the PR. I have created an issue for the PR i.e. #1148 as per our suggested work flow for a PR. Please update the commit message as `Issue #1148 Reference the latest OpenShift doc `

**Comment by gbraad** [comment]
Isn't there a fixed version of the documentation? Linking to the latest might result in inconsistencies in supported functionality.

**Comment by praveenkumar** [comment]
@gbraad https://docs.openshift.org/ does have drop-down to select a specific version but again using minishift user can deploy openshift v1.4 to 3.6.rc so I think putting latest might make sense. On second thought we can only use same versioned doc which we support by default (like currently we have by default 1.5.1). @minishift/minishift-dev wdyt?

**Comment by gbraad** [comment]
Actually my thought. We currently point to v1.5.1 as the default, and therefore this should be reflected in your documentation.

This, however, means that each change of the default version would also mean a change in the documentation. This is bound to go wrong... but referring to the latest feels even worse, as this might support newer options we do not have/support in the deployed default version. This is why I suggested a fixed version as preferred option

**Comment by liangxia** [comment]
$ pwd
/opt/github/minishift
$ grep -rE 'docs.openshift.com/' * | wc -l
1
$ grep -rE 'docs.openshift.org/' * | wc -l
27
$ grep -rE 'docs.openshift.org/latest' * | wc -l
27

You can see most part are referencing the latest.

**Comment by gbraad** [comment]
Which we might have to reconsider? @ThatDocsLady, WDYT? Point to latest or
have a inclusion handle the links to a fixed version? If not, we can go
ahead with this...

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by thatdocslady** [comment]
@gbraad we usually reference the latest docs as they reflect the most updated information, and since we only publish *our* latest docs, they should be in sync. OSO usually publishes the latest or only one version back for their upstream anyway, so if we reference a specific version then it might break in a few months anyway. I'm happy with this link format :)

**Comment by hferentschik** [comment]
ok to test

**Comment by hferentschik** [comment]
Merged. As @thatdocslady, we usually reference the latest Origin docs.

**Pull request merged**
