### PR TITLE
Issue #147 Removing the vendor directory

### PR DESCRIPTION
**Pull request by hferentschik**
Addresses issue #147 

Removing the vendor directory. Dependencies managed by Glide.

### CODE REVIEW

**Comment by hferentschik** [comment]
Closing and re-opening to trigger a new TravisCI build

**Comment by budhrg** [comment]
@hferentschik 

Error

```
The command "curl https://glide.sh/get | sh" failed and exited with 1 during .
```

**Comment by hferentschik** [comment]
> The command "curl https://glide.sh/get | sh" failed and exited with 1 during .

I know. It is a GitHub issue. glide.sh downloads from api.github.com which has a rate limit. Given that I repushed now so often, I exceeded the rate limit. One could just wait for an hour or so, but I think I found a workaround - https://github.com/Masterminds/glide/issues/639

BTW, you can get the same working with the minishift codebase where the download of the binaries is also via api.github.com. You can work around this by setting an environment variable specifying a github token. Authenticated client have a higher rate. 

In fact the latest CI build actually worked now for Glide, but failed for the openshift download. Nothing much to do there right now. Need to leave it alone for a bit.

**Comment by hferentschik** [comment]
Seems the CI builds are happy now. On both pull requests :-)

**Comment by hferentschik** [comment]
> The travis config can probably be tidied up a bit but LGTM for now.

Ok. More changes to the Travis config in the next pull request. Work in progress in this area as well :-)

**Comment by jimmidyson** [comment]
BTW also not a big fan personally of automating squashing commits via github UI - feel like that should be a human decision based on whether commits should actually be squashed (related to same functionality). I'm personally happy to have more than 1 commit pushed for a PR if those commits show distinct changes. WDYT?

**Comment by LalatenduMohanty** [comment]
> BTW also not a big fan personally of automating squashing commits via github UI - feel like that should be a human decision based on whether commits should actually be squashed (related to same functionality). I'm personally happy to have more than 1 commit pushed for a PR if those commits show distinct changes.

Agree. IMO the squashing if required should be done by the PR contributor.

**Pull request merged**
