### PR TITLE
Issue #1574 Fixing profile set to work always

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
This issue was introduced in commit c2aeff6

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by anjannath** [comment]
it seems centos ci is failing because of a broken link in the docs, in the driver-troubleshooting section.
this link https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell

**Comment by LalatenduMohanty** [comment]
@anjannath Right. Also quick searches in internet does not give me an article which can not replace it.

**Comment by anjannath** [comment]
retest this please

**Comment by budhrg** [comment]
> it seems centos ci is failing because of a broken link in the docs, in the driver-troubleshooting section.
this link https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell

Seems to be network glitch. I am able to access https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell and hence CI is passing now.

**Pull request merged**
