### PR TITLE
[Do no merge] Revert "Issue #3386 Temporarily disable link checking for master branch"

### PR DESCRIPTION
**Pull request by anjannath**
Reverts minishift/minishift#3387

### CODE REVIEW

**Comment by gbraad** [comment]
this needs to go in, right?

**Comment by anjannath** [comment]
@gbraad Yes, currently it fails while combining minishift docs with openshift docs, hence the centos ci failures, i need to get hold of a slave and investigate inside it why it fails..
```
09:43:16 + mkdir -p minishift/docs/master
09:43:16 + cp -r openshift-docs/_preview/openshift-origin minishift/docs/master/
09:43:16 cp: cannot stat ‘openshift-docs/_preview/openshift-origin’: No such file or directory
```

The `openshift-docs/_preview/openshift-origin` directory is supposed to be created when building the docs for origin.

**Comment by anjannath** [comment]
retest this please

**Comment by anjannath** [comment]
Failures related to #3389

**Pull request closed without merging**
