### PR TITLE
Issue #3051 Remove b2d iso support completely

### PR DESCRIPTION
**Pull request by anjannath**

### CODE REVIEW

**Comment by gbraad** [comment]
Lgtm, but no CentOS CI?

**Comment by anjannath** [comment]
The centos ci job failed while deploying `nodejs-ex`, i know that's a known failure, but the error msg looked different than before, so triggered it again, just to be sure!

**Comment by gbraad** [comment]
@anjannath what is up with CentOS CI ?

I think this should be merged ASAP

**Comment by anjannath** [comment]
retest this please

**Comment by anjannath** [comment]
retest this please

**Comment by LalatenduMohanty** [comment]
Thanks @anjannath

**Pull request merged**
