### PR TITLE
Issue #2900 add write-config flag and cluster start

### LINKED ISSUE #2900: Break cluster up to write-config and then cluster-up
At this moment after VM is provisioned we directly execute `oc cluster up`. I want to add some flags and following flow.

```
$ minishift start --no-provision => exist and does it very well
$ minishift start --write-config => This will just write the cluster up config with whatever parameter user provide as part of start and configs are present in the /var/lib/minishift/base
$ minishift openshift start => this will just do the cluster up using the /var/lib/minishift/base directory as config.
```

All the flags will be behind the experimenting flags and our day to day users are not going to see any change to their flow. This will be helpful for mostly advance users and our own testing purpose. 

We can leverage this to do some other experiment before even implementing.

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #2900 

Steps to test the pull request

```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ minishift start --write-config
$ minishift openshift start
```

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@praveenkumar In terms of directories in /var/lib/minishift/base I think I see the same number of directories. Can you please point me the config file that gets created with --write-config?

**Comment by praveenkumar** [comment]
> Can you please point me the config file that gets created with --write-config?

@LalatenduMohanty it will not create any other directory but this is the flag to create the config directory without initiating the cluster up.

**Comment by LalatenduMohanty** [comment]
CI failure is not related to this PR. 

```
--- Failed steps:
08:44:22 
08:44:22   Scenario: User deploys nodejs example application from OpenShift repository # features/cmd-openshift.feature:50
08:44:22     Then stdout should contain # features/cmd-openshift.feature:53
08:44:22       Error: Output did not match. Expected: 'Run 'oc status' to view your app.', Actual: '--> Found image 93de123 (4 days old) in image stream "openshift/nodejs" under tag "10" for "nodejs"
08:44:22 
08:44:22     Node.js 10.12.0 
08:44:22     --------------- 
08:44:22     Node.js  available as docker container is a base platform for building and running various Node.js  applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
08:44:22 
08:44:22     Tags: builder, nodejs, nodejs-10.12.0
08:44:22 
08:44:22     * The source repository appears to match: nodejs
08:44:22     * A source build using source code from https://github.com/sclorg/nodejs-ex will be created
08:44:22       * The resulting image will be pushed to image stream tag "nodejs-ex:latest"
08:44:22       * Use 'start-build' to trigger a new build
08:44:22     * This image will be deployed in deployment config "nodejs-ex"
08:44:22     * Port 8080/tcp will be load balanced by service "nodejs-ex"
08:44:22       * Other containers can access this service through the hostname "nodejs-ex"
08:44:22 
08:44:22 --> Creating resources with label name=myapp ...
08:44:22 --> Failed
```
https://ci.centos.org/job/minishift-pr/5261/consoleFull

**Comment by praveenkumar** [comment]
>  This PR is failing for me consistently , can you take a look?

@LalatenduMohanty  I tried on clean environment and it works as expected (xhyve), @amitkrout @agajdosi any one of you can try it and let me know if you are facing similar issue?

```console
$ ./minishift start --write-config
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ...................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'docker.io/openshift/origin-cli:v3.11.0' ........ OK
   Importing 'docker.io/openshift/origin-control-plane:v3.11.0' ............. OK
   Importing 'docker.io/openshift/origin-deployer:v3.11.0' .... OK
   Importing 'docker.io/openshift/origin-docker-registry:v3.11.0' .... OK
   Importing 'docker.io/openshift/origin-haproxy-router:v3.11.0' .... OK
   Importing 'docker.io/openshift/origin-hyperkube:v3.11.0' ...... OK
   Importing 'docker.io/openshift/origin-hypershift:v3.11.0' ......... OK
   Importing 'docker.io/openshift/origin-node:v3.11.0' ................ OK
   Importing 'docker.io/openshift/origin-pod:v3.11.0' .... OK
   Importing 'docker.io/openshift/origin-service-serving-cert-signer:v3.11' ... OK
   Importing 'docker.io/openshift/origin-web-console:v3.11.0' ..... OK
   Importing 'openshift/origin-control-plane:v3.11.0' ........... OK
   Importing 'openshift/origin-docker-registry:v3.11.0' ... OK
   Importing 'openshift/origin-haproxy-router:v3.11.0' ..... OK
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.64.74 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I1112 08:33:54.984154    2386 config.go:40] Running "create-master-config"
I1112 08:33:57.525427    2386 config.go:46] Running "create-node-config"
Wrote config to: "/var/lib/minishift/base"


$ ./minishift openshift start
..................................................................................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.64.74 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I1112 08:38:12.482161    2788 flags.go:30] Running "create-kubelet-flags"
I1112 08:38:12.878182    2788 run_kubelet.go:49] Running "start-kubelet"
I1112 08:38:13.071623    2788 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1112 08:42:09.118205    2788 interface.go:26] Installing "kube-proxy" ...
I1112 08:42:09.121060    2788 interface.go:26] Installing "kube-dns" ...
I1112 08:42:09.121102    2788 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1112 08:42:09.121127    2788 interface.go:26] Installing "openshift-apiserver" ...
I1112 08:42:09.121972    2788 apply_template.go:81] Installing "openshift-apiserver"
I1112 08:42:09.122643    2788 apply_template.go:81] Installing "kube-proxy"
I1112 08:42:09.124186    2788 apply_template.go:81] Installing "kube-dns"
I1112 08:42:09.125470    2788 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1112 08:42:21.793082    2788 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I1112 08:44:45.872031    2788 run_self_hosted.go:242] openshift-apiserver available
I1112 08:44:45.873271    2788 interface.go:26] Installing "openshift-controller-manager" ...
I1112 08:44:45.873389    2788 apply_template.go:81] Installing "openshift-controller-manager"
I1112 08:44:52.552233    2788 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding persistent-volumes ...
Adding web-console ...
Adding router ...
Adding registry ...
Adding sample-templates ...
Adding centos-imagestreams ...
I1112 08:44:52.615260    2788 interface.go:26] Installing "persistent-volumes" ...
I1112 08:44:52.615310    2788 interface.go:26] Installing "openshift-web-console-operator" ...
I1112 08:44:52.615338    2788 interface.go:26] Installing "openshift-router" ...
I1112 08:44:52.615363    2788 interface.go:26] Installing "openshift-image-registry" ...
I1112 08:44:52.615389    2788 interface.go:26] Installing "sample-templates" ...
I1112 08:44:52.615436    2788 interface.go:26] Installing "centos-imagestreams" ...
I1112 08:44:52.615607    2788 apply_list.go:67] Installing "centos-imagestreams"
I1112 08:44:52.617071    2788 apply_template.go:81] Installing "openshift-web-console-operator"
I1112 08:44:52.618462    2788 interface.go:26] Installing "sample-templates/mariadb" ...
I1112 08:44:52.618495    2788 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I1112 08:44:52.618521    2788 interface.go:26] Installing "sample-templates/django quickstart" ...
I1112 08:44:52.618547    2788 interface.go:26] Installing "sample-templates/rails quickstart" ...
I1112 08:44:52.618572    2788 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I1112 08:44:52.618598    2788 interface.go:26] Installing "sample-templates/sample pipeline" ...
I1112 08:44:52.618623    2788 interface.go:26] Installing "sample-templates/mongodb" ...
I1112 08:44:52.618647    2788 interface.go:26] Installing "sample-templates/mysql" ...
I1112 08:44:52.618674    2788 interface.go:26] Installing "sample-templates/postgresql" ...
I1112 08:44:52.618699    2788 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I1112 08:44:52.618724    2788 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I1112 08:44:52.618811    2788 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I1112 08:44:52.619226    2788 apply_list.go:67] Installing "sample-templates/mariadb"
I1112 08:44:52.619461    2788 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I1112 08:44:52.619702    2788 apply_list.go:67] Installing "sample-templates/django quickstart"
I1112 08:44:52.619987    2788 apply_list.go:67] Installing "sample-templates/rails quickstart"
I1112 08:44:52.620249    2788 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I1112 08:44:52.620474    2788 apply_list.go:67] Installing "sample-templates/sample pipeline"
I1112 08:44:52.620700    2788 apply_list.go:67] Installing "sample-templates/mongodb"
I1112 08:44:52.620987    2788 apply_list.go:67] Installing "sample-templates/mysql"
I1112 08:44:52.621255    2788 apply_list.go:67] Installing "sample-templates/postgresql"
I1112 08:44:52.621521    2788 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I1112 08:45:19.638190    2788 interface.go:41] Finished installing "sample-templates/mariadb" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/mysql" "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/nodejs quickstart"
I1112 08:45:46.546186    2788 interface.go:41] Finished installing "persistent-volumes" "openshift-web-console-operator" "openshift-router" "openshift-image-registry" "sample-templates" "centos-imagestreams"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.74:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


OpenShift Started successfully
```

**Comment by amitkrout** [comment]
Works fine and deployed the default nodejs app on the same running cluster. No failure as such

Tested on - fedora 29 + kvm

**Comment by amitkrout** [comment]
@praveenkumar How this is differ from our regular ```minishift start```. Is it going to replace the regular ```minishift start``` in recent future?

Can you please add a feature file or create test coverage issue, will take it in the current sprint.

**Comment by agajdosi** [comment]
@praveenkumar I was expecting that --write-config will take some parameters to be added, written to config file. One can run it just as you mention in example code above: `minishift start --write-config`. So I am not sure, what that does, from where the written config is taken? How can I specify `initialDelaySeconds: 500`?

Thank you for help, feeling lost in it right now :cold_sweat: .

**Comment by amitkrout** [comment]
@agajdosi AFAIU ```minishift start --write-config``` writes the master config and node config to ```/var/lib/minishift/base``` including pulling the container images and keep the setup ready for ```oc cluster up```. I don't think ```minishift openshift config set --patch``` would be helpful for patching origin config because it needs ```OpenShift``` instance to restart for patching to take effect, and also for other config file changes manual update is the only possibility i can see as of now. For example

-  minishift ssh
-  sudo vi /var/lib/minishift/base/static-pod-manifests/apiserver.yaml
-  Updated the liveness probe as follows
```
livenessProbe:
        initialDelaySeconds: 500
        httpGet:
          scheme: HTTPS
```

And to consume this change run ```minishift openshift start```.@praveenkumar correct me if i am wrong.

**Comment by praveenkumar** [comment]
> correct me if i am wrong.

@amitkrout that's right, @agajdosi so this is nothing to do with our openshift patch command stuff, it is mostly for debug purpose for the specific config change.

**Comment by LalatenduMohanty** [comment]
Tested again and it is working fine.

**Pull request merged**
