### PR TITLE
Issue #2345 Rename miniConfig to minishiftConfig

### LINKED ISSUE #2345: Need to be consistent with package name for pkg/minishift/config
Currently, we have two forms

- `minishiftConfig` - https://github.com/minishift/minishift/search?utf8=%E2%9C%93&q=minishiftConfig&type=

and

- `miniConfig` - https://github.com/minishift/minishift/search?utf8=%E2%9C%93&q=miniConfig&type=

### PR DESCRIPTION
**Pull request by budhrg**
Fix #2345

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Integration test failed 
```
12:42:58 --- Failed steps:
12:42:58 
12:42:58   Scenario: Deployed Node.js application is available # features/cmd-openshift.feature:104
12:42:58     Then with up to "5" retries with wait period of "1000ms" the "body" of HTTP request to "/" of service "nodejs-ex" in namespace "myproject" contains "Welcome to your Node.js application on OpenShift" # features/cmd-openshift.feature:106
12:42:58       Error: Server returned error on url: http://nodejs-ex-myproject.192.168.42.64.nip.io/
```

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by gbraad** [comment]
I think this is a very needless change... if you really want consistency in this, you would have to put aliases in front of all package imports for this package. If you would search the code for `minishiftConfig` you are doing it wrong, as you would have to search for [`"github.com/minishift/minishift/pkg/minishift/config"`](https://github.com/minishift/minishift/search?utf8=%E2%9C%93&q=%22github.com/minishift/minishift/pkg/minishift/config%22&type=)

**Comment by LalatenduMohanty** [comment]
Agree with @gbraad. I think I mentioned this in IRC. But now that the PR is here I would suggest we accept it.

**Comment by gbraad** [comment]
sure, but keep this meaningful in future => add value

**Comment by LalatenduMohanty** [comment]
retest this please.

**Pull request merged**
