### PR TITLE
Issue #72 Add update command

### PR DESCRIPTION
**Pull request by dharmit**
`minishift update` prompts user to update minishift if a newer version
is available

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@dharmit Does this PR work for you? I think it should not as you need to also fix https://github.com/minishift/minishift/issues/204#issuecomment-268503443  to make it work.

**Comment by hferentschik** [comment]
@dharmit, thanks for the pull request. Have you actually tested it. Adding the update command is one part, but the release format has changed as well. The binaries were released directly before, but now they are in zip/tar bundles. AFAIR _MaybeUpdateFromGithub_ downloads from the release page which will be the bundle, not the extracted binary. 

To make this work, one has to download the bundle, unpack it and then do the binary update.

**Comment by hferentschik** [comment]
add to whitelist

**Comment by dharmit** [comment]
@LalatenduMohanty @hferentschik Thanks for the explanation. It helps a lot. I'll close this PR for time being and work on the next part which is downloading the tar/zip and unpacking it. Will create a new PR once I've done that.

**Pull request closed without merging**
