### PR TITLE
[WIP] Rollout check with goroutines

### PR DESCRIPTION
**Pull request by gbraad**
DO NOT MERGE

### CODE REVIEW

**Comment by gbraad** [comment]
Basic scenario works: https://ci.centos.org/job/minishift-pr/1463/console

**Comment by gbraad** [comment]
retest this please

**Comment by gbraad** [comment]
Requesting two services fails, while in a small scale test this works as expected. Probably a stupid typo...

**Comment by gbraad** [comment]
when dealing with channels... do not do:

```go
if strings.Contains(output, expected) {
   done <- true
}
done <- false
```

but ALWAYS do:

```go
if strings.Contains(output, expected) {
   done <- true
} else {
   done <- false
}
```

**Comment by gbraad** [comment]
I broke it down into a smaller application: https://gist.github.com/gbraad/c2cba6cde46eb7968c5e8be974371dde

and as mentioned in the previous message. If you do not use an `else` condition block, the channel will always receive `false` for the successive calls.

**Comment by gbraad** [comment]
retest this please

**Comment by hferentschik** [comment]
Will this supersede #986?

**Comment by gbraad** [comment]
@hferentschik nope. it is a bad changeset anyways, as it got branched of a wrong point and changes some of the logic. If I am happy with how it works I'll incorporate it in the other PR.

**Comment by hferentschik** [comment]
Got you

**Comment by gbraad** [comment]
OK, so it can run to completion now.
Time to optimize the goroutine and prevent it from blocking on the channel receive.

**Comment by gbraad** [comment]
Cart failed... as usual I should say... ?

**Comment by gbraad** [comment]
Integrated in the CoolStore PR #986

**Pull request closed without merging**
