### PR TITLE
[WIP] Issue #1857 Fix xpaas-addon test

### LINKED ISSUE #1857: Nightly test is failing for addon-xpaas integration test for minikube ISO
### General information

  * Minishift version: v1.10.0
  * OS: Linux ~~/ macOS / Windows~~
  * Hypervisor: KVM ~~/ xhyve / Hyper-V / VirtualBox~~

Currently the failure is intermittent in CentOS and B2D but more consistent in Minikube. Though Minikube nightly failed for other issues as well.

* https://ci.centos.org/job/minishift-nightly-minikube/13/consoleFull
* https://ci.centos.org/job/minishift-nightly-b2d/13/consoleFull
* https://ci.centos.org/job/minishift-nightly-centos/13/console

### Steps

https://github.com/minishift/minishift/blob/master/test/integration/features/addon-xpaas.feature#L19-L31

Running as part of CI, but this is basically the following:

   * `minishift addons enable xpaas`
   * `minishift start --iso-url minikube`

### Expected

addon-xpaas integration test should pass

### Actual

addon-xpaas integration test is failing

```console
00:07:38   Scenario Outline: User deploys, checks out and deletes several templates from XpaaS imagestream                                   # features/addon-xpaas.feature:19
00:08:53     Given Minishift has state "Running"                                                                                             # integration_test.go:164 -> *Minishift.shouldHaveState
00:08:53     When executing "oc new-app <template-name>" succeeds                                                                            # integration_test.go:695 -> executingOcCommandSucceedsOrFails
00:08:53     And services "<service-name>" rollout successfully                                                                              # integration_test.go:196 -> *Minishift.rolloutServicesSuccessfully
00:08:53     Then body of HTTP request to "<http-endpoint>" of service "<service-name>" in namespace "myproject" contains "<expected-hello>" # integration_test.go:768 -> getRoutingUrlAndVerifyHTTPResponse
00:08:53     And status code of HTTP request to "<http-endpoint>" of service "<service-name>" in namespace "myproject" is equal to "200"     # integration_test.go:768 -> getRoutingUrlAndVerifyHTTPResponse
00:08:53     And executing "oc delete all --all" succeeds                                                                                    # integration_test.go:695 -> executingOcCommandSucceedsOrFails
00:08:53 
00:08:53     Examples: Required information to test the templates
00:08:53       | template-name    | service-name | http-endpoint | expected-hello                        |
00:08:53       | datagrid65-basic | datagrid-app | /             | Welcome to the JBoss Data Grid Server |
01:33:43       | eap64-basic-s2i  | eap-app      | /index.jsf    | Welcome to JBoss!                     |
01:33:43         Not all successfully rolled out
01:33:45       | eap70-basic-s2i  | eap-app      | /index.jsf    | Welcome to JBoss!                     |
01:33:45         Command 'new-app eap70-basic-s2i' did not execute successfully. cmdExit: 1, cmdErr:     error: services "eap-app" already exists
01:33:45     error: routes.route.openshift.io "eap-app" already exists
01:33:45     error: imagestreams.image.openshift.io "eap-app" already exists
01:33:45     error: buildconfigs.build.openshift.io "eap-app" already exists
01:33:45     error: deploymentconfigs.apps.openshift.io "eap-app" already exists
```

### Logs

https://ci.centos.org/job/minishift-nightly-minikube/3/consoleFull

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1857

### CODE REVIEW

**Comment by praveenkumar** [comment]
retest it please.

**Comment by praveenkumar** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
Closing as of now since it was created for testing purpose.

**Pull request closed without merging**
