### PR TITLE
Issue #2532 Improve image export functionality

### PR DESCRIPTION
**Pull request by praveenkumar**
How to test
--------------

Try to export all the images from the running minishift without using this PR.

```
$ time ./minishift image export --all 
```

Now use this PR.
```
$ minishift_pr image delete --all
$ time minishift_pr image export --all
```

```
$ time ./minishift image export --all <= no longer import all the images layer
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'............. OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'.... OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'.... OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'.... OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'.... OK
Exporting 'docker.io/openshift/origin:v3.9.0'... OK

real	1m8.501s
user	0m4.342s
sys	0m2.946s

$ time ./minishift image export --all  <= same here
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'. OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'. OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'. OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'. OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'. OK
Exporting 'docker.io/openshift/origin:v3.9.0'. OK

real	0m13.388s
user	0m0.106s
sys	0m0.126s
```

### CODE REVIEW

**Comment by praveenkumar** [comment]
@jorgemoralespou This will make you bit happy but we can't do anything from the import performance or if you are offline and then exporting images.

```
# This is what minishift do in background when you export a new image and not present in the docker-daemon
$ time (docker pull fedora && skopeo copy --src-cert-dir /home/prkumar/.minishift/certs --src-daemon-host tcp://192.168.42.138:2376  docker-daemon:fedora:latest oci:fedora)
Using default tag: latest
Trying to pull repository docker.io/library/fedora ... 
latest: Pulling from docker.io/library/fedora
e71c36a80ba9: Pull complete 
Digest: sha256:7ae08e5637170eb47c01e315b6e64e0d48c6200d2942c695d0bee61b38c65b39
Status: Downloaded newer image for docker.io/fedora:latest
Getting image source signatures
Copying blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
 250.51 MB / 250.51 MB [===================================================] 16s
Copying config sha256:5415dde2eeab8b18b37d43db94983e3c8f5e3f79c9c5f64ded360ae0c38204d6
 1.31 KB / 1.31 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

real	0m47.103s
user	0m17.057s
sys	0m3.730s

$ time minishift image export fedora
bash: minishift: command not found...

real	0m0.220s
user	0m0.008s
sys	0m0.012s
[prkumar@local bin]$ time ./minishift image export fedora
Exporting 'fedora:latest'................... OK

real	0m47.734s <= No difference around the performance.
user	0m16.834s
sys	0m3.733s
```

**Comment by jorgemoralespou** [comment]
@praveenkumar, exporting an image alone should make no difference. The difference needs to come when exporting multiple images that share layers, and the improvement needs to come because of later reusability, if the layer is present should not be copied.

**Comment by praveenkumar** [comment]
>  exporting an image alone should make no difference. The difference needs to come when exporting multiple images that share layers, and the improvement needs to come because of later reusability, if the layer is present should not be copied.

@jorgemoralespou that is something this PR now resolve, give it a try :)

**Comment by jorgemoralespou** [comment]
@praveenkumar can you point me to the CI generated binary for the PR? I can't build minishift myself

**Comment by praveenkumar** [comment]
@jorgemoralespou http://artifacts.ci.centos.org/minishift/minishift/pr/2564/ you can get it from here.

**Comment by jorgemoralespou** [comment]
@praveenkumar I tested a bit the PR and it seems that it could provide benefit only if the image has been updated, which happens not quite often, only for those tag with latest (or a rolling tag).

I don't see any difference when I export an image using minishift in this PR compared to using stock minishift, in fact, caching one image when cache is empty is slightly slower.

I would love a description on what use cases would this PR benefit, as I haven't seen any improvement in my regular work.

**Comment by praveenkumar** [comment]
> I don't see any difference when I export an image using minishift in this PR compared to using stock minishift, in fact, caching one image when cache is empty is slightly slower.

@jorgemoralespou how did you tested this PR can you put steps so I can try. Below is my way of testing.

```
== Without this PR ===
$ minishift image delete --all
$ minishift start 
$ minishift export --all => check the time 

== With this PR ===
Do all the above step and check the time.
```

**Comment by gbraad** [comment]
More input is needed.... plus awaiting the response of @runcom related to improvements related to the containers/image library

**Comment by agajdosi** [comment]
@praveenkumar I observe an improvement on Fedora 28, tested on both binaries with following steps:
```
minishift delete
rm -fr ~/.minishift
minishift start
(wait until images are caches)
minishift image export --all
```

minishift v1.21.0:
```
[agajdosi@dhcp-24-156 minishift]$ time minishift image export --all
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'.......................^[[F..................... OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'......................... OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'................................................ OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'................ OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'.......................... OK
Exporting 'docker.io/openshift/origin:v3.9.0'............................................. OK

real	11m45.792s
user	4m7.079s
sys	1m2.164s
```
with this pr:
```
[agajdosi@dhcp-24-156 minishift]$ time minishift_pr image export --all
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'................................... OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'.................. OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'..................................... OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'............ OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'.................... OK
Exporting 'docker.io/openshift/origin:v3.9.0'...................................... OK

real	8m12.138s
user	0m25.034s
sys	0m57.235s
```

**Comment by praveenkumar** [comment]
Ping @jorgemoralespou can you retest this artifact links => http://artifacts.ci.centos.org/minishift/minishift/pr/2564/

**Comment by LalatenduMohanty** [comment]
@praveenkumar I tested for image export I can see improvement with this PR , but need to run more tests on this. 

With this PR
```
$ time minishift images export --all
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'............. OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'...... OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'............ OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'... OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'..... OK
Exporting 'docker.io/openshift/origin:v3.9.0'.......... OK

real	1m44.027s
user	0m23.250s
sys	0m26.172s
````

Without this PR
```
$ time minishift images export --all
Exporting 'docker.io/openshift/origin-deployer:v3.9.0'............................. OK
Exporting 'docker.io/openshift/origin-docker-registry:v3.9.0'.................. OK
Exporting 'docker.io/openshift/origin-haproxy-router:v3.9.0'.............................. OK
Exporting 'docker.io/openshift/origin-pod:v3.9.0'........... OK
Exporting 'docker.io/openshift/origin-web-console:v3.9.0'................. OK
Exporting 'docker.io/openshift/origin:v3.9.0'............................ OK

real	6m7.114s
user	4m10.698s
sys	2m22.727s
```

**Comment by praveenkumar** [comment]
@minishift/minishift-dev  Can we merge this now?

**Comment by LalatenduMohanty** [comment]
Thanks @praveenkumar

**Pull request merged**
