### PR TITLE
Issue #246 Disabling automatic update

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I do not think we need test for this as we will revert back to automatic update in next to next release. However I am open to suggestion. 
The PR passed all my testing. Here are the steps to test the PR. 
* Reduce the version in Version file and then build the minishift binary
* Check the version of the binary using `minishift version`
* Run `minishift start` command and it should not ask for updating to the latest release.

**Comment by LalatenduMohanty** [comment]
I can reproduce the travis failure manually on the master branch too. However `make test` passing fine both in the PR branch and master branch. 

```
$ make cross test fmtcheck prerelease
CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build --installsuffix cgo -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.1 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/darwin-amd64/minishift ./cmd/minikube
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build --installsuffix cgo -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.1 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/linux-amd64/minishift ./cmd/minikube
CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build --installsuffix cgo -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.1 -X github.com/minishift/minishift/pkg/version.openshiftVersion=v1.3.1 -s -w -extldflags '-static'" -o ./out/windows-amd64/minishift.exe ./cmd/minikube
?       github.com/minishift/minishift  [no test files]
?       github.com/minishift/minishift/cmd/minikube     [no test files]
ok      github.com/minishift/minishift/cmd/minikube/cmd 4.548s
ok      github.com/minishift/minishift/cmd/minikube/cmd/config  0.014s
?       github.com/minishift/minishift/deploy/minikube  [no test files]
ok      github.com/minishift/minishift/pkg/minikube/cluster     0.035s
?       github.com/minishift/minishift/pkg/minikube/config      [no test files]
?       github.com/minishift/minishift/pkg/minikube/constants   [no test files]
ok      github.com/minishift/minishift/pkg/minikube/kubeconfig  0.017s
ok      github.com/minishift/minishift/pkg/minikube/machine     0.019s
ok      github.com/minishift/minishift/pkg/minikube/openshiftversions   0.019s
ok      github.com/minishift/minishift/pkg/minikube/sshutil     0.490s
?       github.com/minishift/minishift/pkg/minikube/tests       [no test files]
ok      github.com/minishift/minishift/pkg/minikube/update      0.018s
ok      github.com/minishift/minishift/pkg/minishift/cache      2.406s
ok      github.com/minishift/minishift/pkg/minishift/provisioner        0.905s
ok      github.com/minishift/minishift/pkg/minishift/registration       1.278s
?       github.com/minishift/minishift/pkg/testing      [no test files]
?       github.com/minishift/minishift/pkg/testing/cli  [no test files]
ok      github.com/minishift/minishift/pkg/util 0.013s
?       github.com/minishift/minishift/pkg/util/archive [no test files]
ok      github.com/minishift/minishift/pkg/util/github  7.887s
?       github.com/minishift/minishift/pkg/util/os      [no test files]
?       github.com/minishift/minishift/pkg/version      [no test files]
/Users/lmohanty/code/gocode/src/github.com/minishift/minishift/pkg/minikube/cluster/assets.go
[WARN] Fix formatting issues with 'make fmt'
./prerelease.sh
Checking boilerplate...
Boilerplate missing in: ././pkg/minikube/cluster/assets.go.
make: *** [prerelease] Error 1
```

**Comment by hferentschik** [comment]
@LalatenduMohanty did you try turning of the network as well and then start/stop?

**Comment by hferentschik** [comment]
I tried w/ disconnecting from network. Seems ok. Merged, thanks.

**Pull request closed without merging**
