### PR TITLE
[WIP] Issue #2658 Making the default OpenShift version as  3.10.0

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
IMO we should merge this after fixing #2661

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by LalatenduMohanty** [comment]
retest this please

**Comment by agajdosi** [comment]
@LalatenduMohanty Some failures looks similar to what is reported here: https://github.com/openshift/origin/issues/20544.

**Comment by praveenkumar** [comment]
retest this please.

**Comment by praveenkumar** [comment]
One of the failure reason https://github.com/openshift/origin/pull/20236

**Comment by budhram** [comment]
> One of the failure reason openshift/origin#20236

Just wondering why it is not reproducible locally.

**Comment by LalatenduMohanty** [comment]
Closing it in favor of #2702

**Pull request closed without merging**
