### PR TITLE
Issue #3173 Use helper function to get status instead of running `minishift status` command

### LINKED ISSUE #3173: Fix periodic update of status icon color for system tray
While working on #3058 (see: https://github.com/minishift/minishift/pull/3058#issuecomment-460550738) we found out that the status icon was incorrectly updated this happened due to the command `minishift status --profile <name>` returning some `iaddress:port` instead of correct o/p. 
screenshot 2019-02-05 at 1 52 34 pm

Console log from the `getStatus()` function:

```bash
2019-02-20 13:10:32.157 minishift[1663:6381937] Done loading image
2019-02-20 13:10:32.157 minishift[1663:6381937] Done setting image
Minishift:  Stopped
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  Unknown
CacheUsage: 1.828 GB (used by oc binary, ISO or cached images)
 
2019-02-20 13:10:37.547 minishift[1663:6381939] Done loading image
2019-02-20 13:10:37.547 minishift[1663:6381939] Done setting image
Minishift:  Stopped
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  Unknown
CacheUsage: 1.828 GB (used by oc binary, ISO or cached images)
 
2019-02-20 13:10:42.937 minishift[1663:6381939] Done loading image
2019-02-20 13:10:42.937 minishift[1663:6381939] Done setting image
127.0.0.1:64791                                                   <=== instead of minishift status o/p
 
2019-02-20 13:10:57.982 minishift[1663:6381939] Done loading image
2019-02-20 13:10:57.982 minishift[1663:6381939] Done setting image
127.0.0.1:64794                                                   <=== instead of minishift status o/p
 
2019-02-20 13:11:13.025 minishift[1663:6381937] Done loading image
2019-02-20 13:11:13.025 minishift[1663:6381937] Done setting image
2019-02-20 13:11:13.025 minishift[1663:6381937] Done loading image
2019-02-20 13:11:13.025 minishift[1663:6381937] Done setting image
127.0.0.1:64810                                                   <=== instead of minishift status o/p
```

NOTE: I have tried to reproduce this by running the same command `minishift status --profile <name>` repeatedly from a terminal and it works fine.

<strike>Since, it is showing incorrect status, till we find the cause for it, I suggest we remove the following piece of code that periodically updates the icons. After which the icons will only change color once a start/stop action is performed from the tray menu.</strike>

Issue is fixed upon using what @LalatenduMohanty Mentioned in https://github.com/minishift/minishift/issues/3173#issuecomment-465513581

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #3173

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I am ok with removing the status icon as it will make things consistent with systemtray user experience on Windows

**Comment by LalatenduMohanty** [comment]
@gbraad @praveenkumar If we can decide this today (asap) it will be helpful from cdk 3.8 timeline.

**Comment by anjannath** [comment]
@LalatenduMohanty We don't need to remove anything now, the issue is fixed when `cmdUtil.GetVMStatus()` is used. I am going to update this PR and the related issue accordingly.

**Comment by gbraad** [comment]
What is/was the issue with the status icon?

**Comment by LalatenduMohanty** [comment]
@gbraad @praveenkumar Ignore my previous comment as @anjannath has actually fixed the issue so we do not need to remove the status icons anymore.

**Comment by LalatenduMohanty** [comment]
The original issue is fixed, but I am seeing a new issue, I am getting this error when I am trying to start/stop through the system tray. However `minishift` CLI seems to work fine. 

```
Last login: Wed Feb 20 18:41:44 on ttys001
/tmp/minishift.stop ; exit;
Lalatendus-MacBook-Pro:~ lmohanty$ /tmp/minishift.stop ; exit;
F0220 18:44:38.577603   10889 client.go:45] Unsupported driver: xhyve
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by LalatenduMohanty** [comment]
> he original issue is fixed, but I am seeing a new issue, I am getting this error when I am trying to start/stop through the system tray. However `minishift` CLI seems to work fine.

I was testing master not the PR :(

**Pull request merged**
