### PR TITLE
[WIP] Test minikube iso

### LINKED ISSUE #1993: Minikube nightly job is failing on "ruby-ex" roll-out unsuccessful step
### Expected
Minikube nightly job should succeed.

### Logs

See https://ci.centos.org/job/minishift-nightly-minikube/51/consoleFull

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1993 
Testing Minikube nightly ISO

### CODE REVIEW

**Comment by budhrg** [comment]
Here, we go why `ruby-ex` rollout wasn't successful.

Somehow, github.com is having some issue. See screenshot.

screenshot from 2018-02-08 21-12-14 

/cc @minishift/minishift-dev

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by praveenkumar** [comment]
@budhrg still experimenting or we can close this?

**Comment by budhrg** [comment]
Still experimenting.

**Comment by budhrg** [comment]
@praveenkumar Found something interesting here https://github.com/minishift/minishift/issues/1993#issuecomment-367349795

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
retest this  please

**Comment by budhrg** [comment]
retest this please

**Comment by budhrg** [comment]
Closing it as it was created for testing purpose.

**Pull request closed without merging**
