### PR TITLE
Issue #3161 Update xPaaS add-on to include EAP 7.2.0 GA

### LINKED ISSUE #3161: Update xPaaS add-on to include EAP 7.2.0 GA imagestreams and templates
https://github.com/openshift/openshift-ansible/commit/86222d1f424a741071746f3d460c9286a4d2dc30

### PR DESCRIPTION
**Pull request by agajdosi**
Fixes #3161

Steps to test the pull request

  1. m start
  2. m addons apply redhat-registry-login
  3. m addons apply xpaas
  4. try deployment of some applications

### CODE REVIEW

**Comment by agajdosi** [comment]
retest this please

**Comment by anjannath** [comment]
@agajdosi LGTM, once you change back the makefile, we can merge

**Comment by agajdosi** [comment]
retest this please

**Comment by agajdosi** [comment]
@anjannath Makefile reverted, this can be thus merged.

**Comment by anjannath** [comment]
@agajdosi Need to wait for the ci to finish, will merge once its done!

**Pull request merged**
