### PR TITLE
minor: fix small typo in che addon README

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by gbraad** [comment]
add to whitelist

**Comment by amitkrout** [comment]
I think this pr is created after pull request template got merged. Wondering why the pull request template doesn't reflect here. @vorburger did you delete anything in the pr description area while sending the pr ?

**Comment by vorburger** [comment]
Yes I manually deleted the template.

**Comment by LalatenduMohanty** [comment]
@vorburger Thanks for the PR. As per contributor guideline https://github.com/minishift/minishift/blob/master/CONTRIBUTING.adoc we need issue for each PR as it helps us tracking each change. I have created an issue https://github.com/minishift/minishift/issues/2700 for the PR you created. 

Please update the commit message with the issue number e.g. `Issue #2700 fix small typo in che addon README` or we can do the change for you and then merge the PR.

**Comment by vorburger** [comment]
Please do this change for me and merge.

>

**Comment by budhram** [comment]
Merged and thanks for the patch @vorburger :+1:

**Pull request closed without merging**
