### PR TITLE
Issue #435 Enable CI to get triggered when a push to master occurs

### LINKED ISSUE #435: Enable CI to get triggered when a push to master occurs
Currently, CI only get triggered when PR is sent.

We need to trigger it when PR get merged with master.

It should also store the generated artifacts as well.

See https://github.com/minishift/minishift/issues/415#issuecomment-280584915

### PR DESCRIPTION
**Pull request by budhrg**
Fix #435

### CODE REVIEW

**Comment by budhrg** [comment]
Will rebase it once, it PR https://github.com/minishift/minishift/pull/444 is merged.

**Comment by hferentschik** [comment]
@budhrg will that fix the problem? Could you rebase please?

**Comment by budhrg** [comment]
@hferentschik  Rebased. IMO, it will fix since the build was triggered last time but due to error in conditional check if failed to upload - https://ci.centos.org/job/minishift-build-master/5/console

```
00:16:53.281 + set +x
00:16:53.281 centos_ci.sh: line 91: [[: origin/master: division by 0 (error token is "master")
00:16:53.373 rsync: mkdir "/minishift-build-master/pr" (in minishift) failed: No such file or directory (2)
00:16:53.374 rsync error: error in file IO (code 11) at main.c(587) [Receiver=3.0.9]
00:16:53.474 rsync: read error: Connection reset by peer (104)
00:16:53.475 rsync error: error in rsync protocol data stream (code 12) at io.c(764) [sender=3.0.9]
00:16:53.480 Connection to 172.19.3.68 closed.
```

**Comment by hferentschik** [comment]
ok, thanks

**Pull request merged**
