### PR TITLE
Issue #950  Adding information of env and persistent config settings 

### PR DESCRIPTION
**Pull request by hferentschik**
- Making 'b2d' default for ISO URL to shorten help display

Addresses issue #950.

### CODE REVIEW

**Comment by hferentschik** [comment]
>  However we need to change https://docs.openshift.org/latest/minishift/using/managing-minishift.html#environment-variables to tell users how they can use values for flags in minishift start from environment variables i.e. similar to the this PR. At least we should fix the docs to reflect the same.

You are loosing me here. The docs contain this information. I basically took it from there. A online docs are more verbose, but effectively the information is the same.

**Comment by LalatenduMohanty** [comment]
> You are loosing me here. The docs contain this information. I basically took it from there. A online docs are more verbose, but effectively the information is the same.

I feel the text in this PR is relatively easy to understand as compared to the docs. Hence the suggestion.

**Comment by hferentschik** [comment]
> I feel the text in this PR is relatively easy to understand as compared to the docs.

I agree. IMO it contains all the information one needs. It does not have to be more complicated than this. The current text on the online docs is a result of making the docs "easier" to understand. Whether this is the case or not depends most likely on the point of view.

**Comment by LalatenduMohanty** [comment]
> Whether this is the case or not depends most likely on the point of view.

@thatdocslady @gbraad @praveenkumar @budhrg WDYT? Should we change the docs similar to the PR text?

**Comment by hferentschik** [comment]
@LalatenduMohanty Just to be clear, what you want is to replace this (in the online docs):

    Minishift allows you to specify command-line flags you commonly use through environment variables. To do so, apply the following rules to the flag you want to set as an environment variable.

    * Apply MINISHIFT_ as a prefix to the flag you want to set as an environment variable. For example, the vm-driver flag of the minishift start command becomes MINISHIFT_vm-driver.

    * Use uppercase characters for the flag, so MINISHIFT_vm-driver in the above example becomes MINISHIFT_VM-DRIVER.

    * Replace - with _, so MINISHIFT_VM-DRIVER becomes MINISHIFT_VM_DRIVER.

With basically a single sentence:

"Prefix the flag with MINISHIFT_, uppercase characters and replace '-' with '_', for example MINISHIFT_VM_DRIVER"

**Comment by praveenkumar** [comment]
To me both looks understandable. I do agree on doc side it' bit complicated but it also provide better context about how actually convert happen.

**Comment by LalatenduMohanty** [comment]
@hferentschik  Actually 
```
* Apply MINISHIFT_ as a prefix to the flag you want to set as an environment variable. For example, the vm-driver flag of the minishift start command becomes MINISHIFT_vm-driver.

* Use uppercase characters for the flag, so MINISHIFT_vm-driver in the above example becomes MINISHIFT_VM-DRIVER.

* Replace - with _, so MINISHIFT_VM-DRIVER becomes MINISHIFT_VM_DRIVER.
```
With

"Prefix the flag with MINISHIFT_, uppercase characters and replace '-' with '_', for example MINISHIFT_VM_DRIVER"

and then proof reading the paragraph again and fix if required.

**Comment by hferentschik** [comment]
> and then proof reading the paragraph again and fix if required.

Sure.

**Comment by jorgemoralespou** [comment]
l liked that the current format has an example along the explanation, so as long as you add the example afterwards, WFM.

**Pull request merged**
