### PR TITLE
Issue #1448 Allow GitLab CI to run against tagged runners

### LINKED ISSUE #1448: Allow GitLab CI to run against tagged runners
At the moment the definition does not specify which runner can handle the build task

Add:
```yaml
  tags:
    - docker
```

### PR DESCRIPTION
**Pull request by gbraad**
Fix #1448 

Tested on:
  * https://gitlab.com/gbraad/minishift/commit/efbaad6e5c1275765536f376f647f1dd59033ba9/pipelines
  * https://gitlab.cee.redhat.com/gbraad/minishift/builds/203897

### CODE REVIEW

**Comment by gbraad** [comment]
Ugh, for some reason that became a merge....

https://github.com/minishift/minishift/pull/1451/commits

**Comment by gbraad** [comment]
do not merge... will have to repush without the merge, and rebased

**Comment by budhrg** [comment]
> do not merge... will have to repush without the merge, and rebased

Ya, pull your PR and saw it.

**Comment by gbraad** [comment]
fixed...

**Comment by budhrg** [comment]
Merged and thanks.

**Comment by gbraad** [comment]
merged?

**Comment by budhrg** [comment]
> merged?

Yes

**Comment by gbraad** [comment]
image

**Closed with unmerged commits**
This pull request is closed, but the `gbraad:issue1448` branch has unmerged commits.

**Comment by budhrg** [comment]
> Closed with unmerged commits
> This pull request is closed, but the gbraad:issue1448 branch has unmerged
> commits.

How do you merge? I reword the commit and merge with upstream master.

**Comment by gbraad** [comment]
I rebase onto master and then merge...

**Pull request closed without merging**
