### PR TITLE
Issue #681 Fix broken link of 'CONTRIBUTING' in 'README'

### PR DESCRIPTION
**Pull request by warmchang**
Addresses issue #681

### CODE REVIEW

**Comment by warmchang** [comment]
Something wrong about the CI?

> [ERROR]	Failed to set version on k8s.io/kubernetes to a9e9cf3b407c1d315686c452bdb918c719c3ea6e: Unexpected error while defensively cleaning up after possible derelict submodule directories
> [ERROR]	Failed to set references: Unexpected error while defensively cleaning up after possible derelict submodule directories (Skip to cleanup)
> Command exited with code 1

**Comment by budhrg** [comment]
retest this please

**Comment by hferentschik** [comment]
Please do not merge, yet. There is an unwanted commit in there as well.

**Comment by hferentschik** [comment]
@warmchang, merged thanks.

Could you please make sure, your master is properly in sync. I accidentally made some changes yesterday which might have got our branch of master out of sync.

Try running the following commands on master:

     $ git reset --hard a0a53180478ec02b3b4811560f2fc0168c298298
     $ git pull

This should get you in sync again.

**Comment by warmchang** [comment]
@hferentschik , thank you for your advice to pull the fresh code from v1.0.0-rc.1 base (a0a53180478ec02b3b4811560f2fc0168c298298).

Is this the accident which you mentioned?

image

Sorry about this, and actually I didn't mean to do that. Maybe this error due to my inconsistent local repo. Anyway, I'll pay attention to it later.

**Pull request closed without merging**
