### PR TITLE
Issue #544 Using grep instead of read in fmtcheck target

### LINKED ISSUE #544: fmtcheck target does not work on Travis CI

### PR DESCRIPTION
**Pull request by hferentschik**
Fix #544

### CODE REVIEW

**Comment by budhrg** [comment]
Interesting :+1:

**Comment by LalatenduMohanty** [comment]
@hferentschik I am confused by this PR. I saw another commit saying"not to be merged" ?

**Comment by hferentschik** [comment]
@LalatenduMohanty this particular commit should not be merged. But I also marked it as WIP again, since there is something else not quite right yet.

**Comment by hferentschik** [comment]
@praveenkumar after some more iterations, I went back to the _grep_ approach.

The wrong if statement syntax for was part of the problem, but there are also issues with _read_. Not sure why it seemed to work at least once with an earlier pull request of mine. 

The current pull request seems to work consistently. I did several iterations of including and removing style violations and in all cases all CI systems either failed or passed.

The _grep_ is imo also easier to take in. Downside is that _grep_ is not Windows friendly, but we use it already in the build, so for now it works for me.

**Comment by praveenkumar** [comment]
LGTM 👍 , I also closed my old PR.

**Comment by hferentschik** [comment]
>  I also closed my old PR.

Ok, thanks.

**Pull request merged**
