### PR TITLE
Issue #1968 Integration tests for Che addon

### PR DESCRIPTION
**Pull request by JPinkney**
This PR adds integration tests for the che addon. The integration tests happen across various stacks and they start a workspace, import a project, run a command for that project, stop workspace, and delete the workspace.

### CODE REVIEW

**Comment by anjannath** [comment]
@JPinkney You need to update you commit message to contain the issue number, i have created #1968
Please update the commit message to contain `Issue #1968` in the begining.

**Comment by anjannath** [comment]
@JPinkney you need to change the commit msg not the PR title. :)

**Comment by LalatenduMohanty** [comment]
@JPinkney The Che add-on is not part of minishift repository so we can not add the test here. We would create separate CI for minishift-addons repository and we can add the test there.

**Comment by budhrg** [comment]
Thanks @JPinkney for the PR. However, as mentioned by @LalatenduMohanty , che addon is not part of minishift repo and we will provide a mechanism in the minishift-addons repo to test the respective addon.

This PR at least give us hint how to come up with that framework. Thanks.

**Comment by agajdosi** [comment]
Taking a look on how we could improve usage of our integration tests as a package. AFAIR I could be able to separate all the basic code for the integration tests and move it into the new package eg. `integration-test`. This would minimize any code in package `integration` which we have now. Ideally only one really short file will remain from this package `integration` - a short integration_test.go file from which the tests will start. This file will import the `integration-test` package. In the minishift-addons we will have modified integration_test.go, which will import extra packages which @JPinkney uses now.

It could look like this:

```
func FeatureContextStarter(s *godog.Suite) {
	integrationTestSuite.FeatureContext(s) // definition of steps we currently use
	FeatureContextCHE(s) // extra steps from CHE package
}
```

**Comment by agajdosi** [comment]
@JPinkney I have created an issue #1970 for opening up the integration test suite to be used as a package outside of the Minishift repository. It works right now, I need to do some cosmetic reordering and hopefully will be able to create the PR on Monday/Tuesday. Once it is merged I will set it up in the minishift-addons repository so you can add the tests for the Che addon. Will inform you.

**Comment by JPinkney** [comment]
Awesome thanks! I guess at this point I'll close this PR and https://github.com/minishift/minishift/issues/1968 can be closed as well

**Pull request closed without merging**
