### PR TITLE
Issue #1833 Use single quotes to highlight commands and some words

### LINKED ISSUE #1833: Use consistent format to show command in the output of any minishift command
### General information

As reference to this https://github.com/minishift/minishift/pull/1731#issuecomment-350985247, we found that during the output of minishift command, we are not consistent in showing command.

See below:
1. Using single quote:
```
$ minishift stop -h
Stops the running local OpenShift cluster. This command stops the Minishift
VM but does not delete any associated files. To start the cluster again, use the 'minishift start' command.
[...]
```

2. Use back tick:
```
$ minishift addon apply
You must specify an add-on name. Run `minishift addons list` to view installed add-ons.
```

Let's decide the format and update all of its occurrences.

### PR DESCRIPTION
**Pull request by bhavin192**
fixes #1833 
I'm trying to maintain consistency across all the outputs/errors.  

PS: I will squash the commits once I finish working on this.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
ok to test

**Comment by budhrg** [comment]
Hi @bhavin192 ,

Is PR ready? If yes, then need to remove `[WIP]`.

**Comment by budhrg** [comment]
retest this please

**Comment by bhavin192** [comment]
@budhrg No it's not ready, I'm still working on it. Haven't pushed the changes to my repo yet.

**Comment by budhrg** [comment]
@bhavin192 Any update?

**Comment by bhavin192** [comment]
@budhrg it's almost done,
here are some places where I'm not able to decide 
1. https://github.com/minishift/minishift/blob/master/pkg/minishift/config/validations.go#L109
2. https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/utils.go#L199
3. https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/utils.go#L247

**Comment by budhrg** [comment]
@bhavin192 

> https://github.com/minishift/minishift/blob/master/pkg/minishift/config/validations.go#L109

Should be `fmt.Errorf("'%s' path is not valid: %v", name, err)`

> https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/utils.go#L199

Should be `errors.Wrapf(err, "open cert file '%s'", src)`
Same for line 202 : `errors.Wrapf(err, "transferring file '%+v'", f)`

> https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/utils.go#L247

`errors.Wrapf(err, "transfering file to machine '%v'", f)`

**Comment by budhrg** [comment]
retest this please

**Comment by LalatenduMohanty** [comment]
@bhavin192 I am getting merge conflicts for this PR, can you please rebase it?

**Comment by bhavin192** [comment]
@LalatenduMohanty done.

**Pull request merged**
