### PR TITLE
Issue #3056 replace <username> with $(whoami)

### PR DESCRIPTION
**Pull request by gastaldi**
This makes it easier to copy/paste the command

### CODE REVIEW

**Comment by anjannath** [comment]
ok to test

**Comment by gastaldi** [comment]
@LalatenduMohanty I don't have any preference, as long as it works when copying and pasting ;)

**Comment by robin-owen** [comment]
@gastaldi Personally, I think `whoami` is the better choice here. While `$USER` should be set in almost any shell, it's not actually guaranteed -- `whoami` should continue to work in those edge cases. :)

**Comment by gbraad** [comment]
why not `$USER` ?

**Comment by gbraad** [comment]
Although `$(whoami)` is understandable, it needs to execute a command. `$USER` is a variable which can, even when not exisitng, easily be defined from the shell.

```
USER=gbraad usermod -a -G libvirt $USER
```

would even work

**Comment by anjannath** [comment]
> `USER=gbraad usermod -a -G libvirt $USER`

This still can't be copy pasted directly from the docs... cause you have to substitute the username.

**Comment by gbraad** [comment]
@anjannath that is the example for override... `$USER` should be generally defined and available from your shell.

**Comment by LalatenduMohanty** [comment]
Thanks @gastaldi

**Pull request merged**
