### PR TITLE
Issue #3287 minishift oc-env errors to stderr, exit non-zero

### LINKED ISSUE #2893: Minishift ip should print to stderr and exit 1 on error
It currently exit 0 (i.e: no issues) and print to STDOUT :

```
% minishift ip;echo $?
Running this command requires a running 'local' VM, but no VM is running.
0
```

This would be helpful when scripting,

### LINKED ISSUE #3287: minishift oc-env should print errors to stderr and exit  non-zero
### General information

Similar to bug #2893 which was closed with no fix and no explanation. 

Clearly this is wrong: Unix  command-line utilities should print errors to stderr (that's what it is for) and return non-zero so scripts can recognize the problem.

It is a particular problem for oc-env since `eval $(minishift oc-env)` is something that would be natural to put in .bashrc, but if the VM isn't running then it attempts to eval the string "Running this command requires a running 'minishift' VM, but no VM is running." which is obviously not a valid bash command.

  * Minishift version: minishift v1.34.0+f5db7cb
  * OS: Linux grommit 5.1.11-300.fc30.x86_64 #1 SMP Mon Jun 17 19:33:15 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  * Hypervisor: KVM

### Steps to reproduce

1. minishift stop
2. minishift oc-env >out.txt 2>err.txt; echo -e "$?\nOUT: $(cat out.txt)\n ERR:$(cat err.txt)"

### Expected

```
1
OUT:
ERR: Running this command requires a running 'minishift' VM, but no VM is running.
```

### Actual

```
0
OUT: Running this command requires a running 'minishift' VM, but no VM is running.
ERR:
```

### Logs
NA

### PR DESCRIPTION
**Pull request by alanconway**
ExitIfNotRunning() exits with status 1 so error goes to stderr.

Any minishift command that requires a running VM to succeed, and
doesn't find one, should signal clearly that it has failed.  In
particular oc-env and docker-env must not print anything to stdout
other than valid shell commands.

Fixes #3287
Fixes #2893

Same as reproducer steps in  Issue #3287

### CODE REVIEW

**Comment by praveenkumar** [comment]
ok to test

**Comment by alanconway** [comment]
Re code coverage - I added feature tests but apparently they're not included in coverage stats.  Should the feature tests be added to the coverage or does this project have another method for unit testing code that is part of a cmd rather than a pkg?

**Comment by praveenkumar** [comment]
@anjannath Can you look into the Centos CI side?

**Comment by alanconway** [comment]
On Wed, Jun 19, 2019 at 10:53 PM Praveen Kumar <notifications@github.com>
wrote:

> @anjannath <https://github.com/anjannath> Can you look into the Centos CI
> side?
>

It's a HTML link checker failure, don't think it has anything to do with my
branch:

*15:44:26* - build/contributing/ci.html*15:44:26*   *  External link
http://artifacts.ci.centos.org/minishift/minishift/pr failed: 404 No
error

*15:44:26* htmlproofer 3.7.2 | Error: HTML-Proofer found 1 failure!

**Pull request closed without merging**
