### PR TITLE
Issue #432 Flags --username and --password should not be placed with common flags

### LINKED ISSUE #432: minishift  flags --username and --password should not be placed with common flags
The general `Flags:` section of minishift usage is for flags which are applicable to all minishift commands. IMO the flags for virtual machine registration is not applicable to all minishift commands.  

```
$ minishift 
Minishift is a command-line tool that provisions and manages single-node OpenShift clusters optimized for development workflows.

Usage:
  minishift [command]

Available Commands:
  config                 Modifies Minishift configuration properties.
  console                Opens or displays the OpenShift Web Console URL.
  delete                 Deletes the Minishift VM.
  docker-env             Sets Docker environment variables.
  get-openshift-versions Gets the list of OpenShift versions available for Minishift.
  ip                     Gets the IP address of the running cluster.
  logs                   Gets the logs of the running OpenShift cluster.
  openshift              Modifies an OpenShift master configuration resource.
  service                Prints the URL for the specified service to the console.
  ssh                    Log in to or run a command on a Minishift VM with SSH.
  start                  Starts a local OpenShift cluster.
  status                 Gets the status of the local OpenShift cluster.
  stop                   Stops the running local OpenShift cluster.
  version                Gets the version of Minishift.

Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --password string                  Password for the virtual machine registration.
      --show-libmachine-logs             Show logs from libmachine.
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --username string                  User name for the virtual machine registration.
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "minishift [command] --help" for more information about a command.
```

### PR DESCRIPTION
**Pull request by praveenkumar**
Fix #432 This patch is mostly a refactor of what we had in past.

### CODE REVIEW

**Comment by budhrg** [comment]
@praveenkumar So, now only commands `start`, `stop` and `delete` contain those flags .

**Comment by praveenkumar** [comment]
@budhrg yes that's what we discuss on the issue.

**Comment by budhrg** [comment]
LGTM :+1: 

Confirmed that `username` and `password` flags appears only for `start`, `stop` and `delete` commands.

```
$ minishift delete -h
Deletes the Minishift VM, including the local OpenShift cluster and all associated files.

Usage:
  minishift delete [flags]

Flags:
      --password string   Password for the virtual machine unregistration.
      --username string   Username for the virtual machine unregistration.

Global Flags:
      --alsologtostderr                  log to standard error as well as files
....
```
Same for start and  stop commands.

```
minishift console -h
Opens the OpenShift Web Console URL in the default browser or displays it to the console.

Usage:
  minishift console [flags]

Flags:
      --machine-readable   Prints OpenShift's IP, port and Web Console URL in Machine readable format
      --url                Prints the OpenShift Web Console URL to the console.

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
....
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar I have added some points to the issue i.e. #432. Lets discuss what we want to do then merge the PR.

**Comment by praveenkumar** [comment]
@LalatenduMohanty I put some comments about what we have already and what should we do as part of this PR.

**Comment by hferentschik** [comment]
Merged, thanks.

**Pull request merged**
