### PR TITLE
[DO NOT MERGE] [WIP] Issue #2021 Revert docker storage driver from overlay to devicemapper

### PR DESCRIPTION
**Pull request by praveenkumar**
- Fall back to CentOS-1.5.0 release instead 1.6.0

### CODE REVIEW

**Comment by praveenkumar** [comment]
@minishift/dev please don't merge it.

**Comment by gbraad** [comment]
@praveenkumar why not?

**Comment by budhrg** [comment]
@gbraad  See https://github.com/minishift/minishift-centos-iso/pull/217

**Comment by gbraad** [comment]
OK , related issue... but moving to ISO v1.5.0 would be enough?

**Comment by anjannath** [comment]
@gbraad If that works we don't have to revert.

**Comment by budhrg** [comment]
@anjannath @gbraad @LalatenduMohanty 
Its working https://github.com/minishift/minishift-centos-iso/pull/217#issuecomment-365258448

**Comment by praveenkumar** [comment]
Closing this now.

**Pull request closed without merging**
