### PR TITLE
Issue #2027 --iso-url is not correct in cmd-config.feature file

### PR DESCRIPTION
**Pull request by amitkrout**
Fix : #2027

### CODE REVIEW

**Comment by amitkrout** [comment]
retest this please

**Comment by praveenkumar** [comment]
@amitkrout @LalatenduMohanty I already have this as part of https://github.com/minishift/minishift/pull/1997/files#diff-0e005e3219f7b717e4717018efeb686f PR so we can close it without merge. It was passing before because our validation are different (iso-url) for config and pre-flight checks.

**Comment by LalatenduMohanty** [comment]
@amitkrout I did not see the same change in https://github.com/minishift/minishift/pull/1997. Otherwise, I would have informed you. Sorry about it. I am closing this.

**Comment by amitkrout** [comment]
@praveenkumar ahh..i saw the feature file change in your pr. Then this pr is not required, however i think you are missing a windows path in your pr. commented https://github.com/minishift/minishift/pull/1997#discussion_r168731335

**Pull request closed without merging**
